import type { SeedProject } from "../types";

export const DATABASE_PROJECTS: SeedProject[] = [
  {
    slug: "implement-a-tiny-database",
    title: "Implement a tiny database",
    summary: "Build a SQLite-style database from a REPL and a tokenizer down to a B-tree on disk.",
    description:
      "Start with a REPL that accepts INSERT and SELECT on a single hard-coded table, storing rows in memory. Then persist them: define a page format, serialise rows into pages, and write pages to a file through a small pager with a cache. Replace the flat row list with a B-tree keyed by the primary key so lookups and inserts stay logarithmic as the file grows.\n\nThe interesting engineering is in the constraints. Pages must be fixed-size, nodes must split without corrupting the tree if the process dies mid-write, and cursors must survive splits. Once the core works you can add a real tokenizer and parser, WHERE clauses, secondary indexes and a write-ahead log. You will never look at a database file the same way again.",
    difficulty: "ADVANCED",
    estimatedHours: 40,
    popularity: 0.9,
    tags: ["databases", "systems", "data-structures"],
    languages: ["c", "rust", "go"],
    concepts: ["page-based storage", "B-trees on disk", "pagers and caching", "SQL tokenising", "cursors and iteration"],
    sourceUrl: "https://cstack.github.io/db_tutorial/",
  },
  {
    slug: "lsm-tree-key-value-store",
    title: "Build an LSM-tree key-value store",
    summary: "Write a LevelDB-style store with a memtable, sorted string tables, compaction and bloom filters.",
    description:
      "Writes go to an in-memory sorted structure (a skip list or balanced tree) and an append-only log for durability. When the memtable fills up, flush it to disk as an immutable sorted table with an index block. Reads check the memtable, then the tables from newest to oldest, using bloom filters to skip tables that cannot contain the key.\n\nCompaction is the heart of the design: merge overlapping tables in the background to reclaim space from overwritten and deleted keys while keeping read amplification bounded. Implement leveled or size-tiered compaction, then measure write amplification, space amplification and read latency under different workloads. This is the storage engine design behind RocksDB, Cassandra and many modern databases.",
    difficulty: "ADVANCED",
    estimatedHours: 30,
    popularity: 0.7,
    tags: ["databases", "systems", "data-structures"],
    languages: ["rust", "go", "java", "cpp"],
    concepts: ["memtables and SSTables", "compaction strategies", "bloom filters", "write-ahead logging", "read/write/space amplification"],
    sourceUrl: "https://github.com/google/leveldb",
  },
  {
    slug: "b-plus-tree-storage-engine",
    title: "Implement a B+ tree storage engine",
    summary: "Build a disk-backed B+ tree with range scans, node splits and merges, and a buffer pool in front.",
    description:
      "B+ trees keep all values in leaf pages linked together, which is what makes range scans in relational databases fast. Implement fixed-size pages, internal nodes with separator keys, leaf nodes with a next pointer, and the split and merge routines that keep the tree balanced under inserts and deletes. Add a buffer pool that pins, evicts and writes back dirty pages so the tree can be far larger than memory.\n\nWrite a fuzz test that performs random operations against your tree and a plain sorted map, checking they agree after every step; this will find bugs no unit test would. Then explore variable-length keys, prefix compression, and latch crabbing so multiple threads can traverse concurrently.",
    difficulty: "INTERMEDIATE",
    estimatedHours: 16,
    popularity: 0.65,
    tags: ["databases", "data-structures", "systems"],
    languages: ["rust", "c", "go", "java"],
    concepts: ["B+ tree splits and merges", "buffer pool management", "page layouts", "range scans", "differential fuzz testing"],
  },
  {
    slug: "write-ahead-log-with-crash-recovery",
    title: "Write-ahead logging with crash recovery",
    summary: "Make a simple store durable with a WAL, then prove it by killing the process at random points.",
    description:
      "Every mutation is appended to a log record with a checksum before the in-memory state changes; on startup, replay the log to rebuild state. That is write-ahead logging, and it is simple to describe and full of subtle failure modes: torn writes at the end of the log, records that were buffered but never fsynced, and logs that grow forever without checkpointing.\n\nBuild a test harness that runs your store as a child process, sends it writes, kills it with SIGKILL at random moments and verifies that every acknowledged write survives and no partial record is ever applied. Add periodic checkpoints and log truncation, group commit to amortise fsync, and compare durability settings against throughput. This project turns 'durable' from a marketing word into something you can demonstrate.",
    difficulty: "INTERMEDIATE",
    estimatedHours: 10,
    popularity: 0.5,
    tags: ["databases", "systems"],
    languages: ["go", "rust", "java"],
    concepts: ["append-only logs", "fsync semantics", "checksums and torn writes", "checkpointing", "crash-injection testing"],
  },
  {
    slug: "sql-query-engine",
    title: "Build a SQL query engine over CSV and Parquet files",
    summary: "Parse SQL, plan it into relational operators and execute it over local files with a Volcano-style iterator model.",
    description:
      "Write a tokenizer and parser for a useful SQL subset (SELECT with projections, WHERE, JOIN, GROUP BY, ORDER BY, LIMIT), turn the syntax tree into a logical plan of relational operators, and execute it by pulling rows through a tree of iterators: scan, filter, project, hash join, hash aggregate, sort. Reading CSV first keeps the I/O simple; adding Parquet later exposes you to columnar layouts.\n\nThe optimiser is where the fun is. Push predicates down below joins, prune unused columns, choose join order by estimated row counts, and use column statistics to skip Parquet row groups. Then vectorise execution to process batches instead of single rows and watch throughput jump. This is a compact tour of what DuckDB, DataFusion and Spark SQL do.",
    difficulty: "ADVANCED",
    estimatedHours: 30,
    popularity: 0.7,
    tags: ["databases", "data-engineering", "compilers"],
    languages: ["rust", "python", "java", "go"],
    concepts: ["SQL parsing", "logical and physical plans", "iterator (Volcano) execution", "hash joins and aggregates", "predicate pushdown"],
    sourceUrl: "https://howqueryengineswork.com/",
  },
  {
    slug: "mvcc-transactions",
    title: "Implement MVCC snapshot isolation",
    summary: "Add multi-version concurrency control to a key-value store so readers never block writers.",
    description:
      "Instead of overwriting values, keep multiple versions of each key stamped with the transaction that created it. A transaction reads the newest version visible to its snapshot and writes new versions that become visible on commit. Readers and writers no longer block each other, which is why PostgreSQL, MySQL InnoDB and most modern databases work this way.\n\nImplement transaction ids, a visibility rule, write-write conflict detection (first committer wins), and garbage collection of versions no active transaction can see. Then write concurrent tests that check invariants such as 'the sum of all account balances never changes' under thousands of interleaved transfers. Try to reproduce the write-skew anomaly that snapshot isolation famously allows, and think about what serialisable would require.",
    difficulty: "ADVANCED",
    estimatedHours: 20,
    popularity: 0.45,
    tags: ["databases", "concurrency"],
    languages: ["rust", "go", "java"],
    concepts: ["multi-version storage", "snapshot visibility rules", "conflict detection", "version garbage collection", "isolation anomalies"],
    sourceUrl: "https://www.postgresql.org/docs/current/mvcc.html",
  },
  {
    slug: "embedded-time-series-database",
    title: "Build an embedded time-series database",
    summary: "Store millions of timestamped samples compactly and answer range and downsampling queries fast.",
    description:
      "Time-series data has a shape you can exploit: timestamps are nearly monotonic and values change slowly. Implement delta-of-delta timestamp encoding and XOR float compression (as in Facebook's Gorilla paper), group samples into time-bounded blocks per series, and index blocks by series labels and time range so a query touches only what it needs.\n\nExpose a small API for appending samples and querying a series over a range with aggregation (avg, min, max per bucket). Add retention that drops old blocks, a write-ahead log for durability, and a tiny query language for label matching. Benchmark bytes-per-sample and query latency against a naive row-per-sample table to see why specialised storage exists.",
    difficulty: "INTERMEDIATE",
    estimatedHours: 18,
    popularity: 0.45,
    tags: ["databases", "data-engineering", "systems"],
    languages: ["go", "rust", "cpp"],
    concepts: ["delta and XOR compression", "block-based storage", "label indexing", "downsampling queries", "retention policies"],
    sourceUrl: "https://prometheus.io/docs/prometheus/latest/storage/",
  },
  {
    slug: "database-migration-tool",
    title: "Build a database migration tool",
    summary: "Write a CLI that applies versioned SQL migrations, tracks state in the database and rolls back safely.",
    description:
      "Every backend team relies on a migration tool, and building one is a compact lesson in operational care. Discover migration files in a directory, order them by version, record applied versions in a table inside the target database, and apply pending ones inside transactions where the database supports transactional DDL. Provide up, down, status and create commands with clear output.\n\nThe details matter: detect a migration file that changed after it was applied (store checksums), lock so two deployers cannot run concurrently, dry-run mode that prints SQL, and helpful errors when a migration fails halfway. Support at least PostgreSQL and SQLite and you will learn how differently databases treat DDL.",
    difficulty: "BEGINNER",
    estimatedHours: 5,
    popularity: 0.5,
    tags: ["databases", "devtools", "cli", "backend"],
    languages: ["typescript", "go", "python"],
    concepts: ["schema versioning", "transactional DDL", "advisory locks", "checksums", "CLI design"],
  },
  {
    slug: "sqlite-file-format-reader",
    title: "Read SQLite database files without SQLite",
    summary: "Parse the SQLite file format by hand to list tables and dump rows straight from the bytes.",
    description:
      "SQLite's on-disk format is public and beautifully compact: a 100-byte header, fixed-size pages, and B-tree pages whose cells hold records encoded as varints and serial types. Write a reader that opens a database file, walks the sqlite_schema table to discover tables, follows each table's root page and decodes every record into typed values.\n\nOnce a full table scan works, add index lookups by walking index B-trees, handle overflow pages for large blobs, and support WHERE on an indexed column. Test against databases you create with the real sqlite3 tool. This project makes B-trees, variable-length encodings and page layouts concrete in a way reading about them never does.",
    difficulty: "INTERMEDIATE",
    estimatedHours: 8,
    popularity: 0.5,
    tags: ["databases", "systems"],
    languages: ["python", "rust", "go", "c"],
    concepts: ["binary file parsing", "varints and record formats", "B-tree page traversal", "overflow pages", "index lookups"],
    sourceUrl: "https://www.sqlite.org/fileformat.html",
  },
  {
    slug: "type-safe-query-builder",
    title: "Build a type-safe query builder",
    summary: "Design a small ORM layer that composes SQL safely and infers result types from the schema.",
    description:
      "Define tables in code, then build queries by chaining select, where, join and orderBy so that the result type is inferred: selecting two columns yields objects with exactly those two fields, a left join makes the joined columns nullable, and a typo in a column name fails to compile. Under the hood, generate parameterised SQL and never interpolate values.\n\nThis is a deep exercise in your language's type system — conditional and mapped types in TypeScript, generics and builders in Kotlin or C#. Add transactions, batching, a migration-aware schema, and a query logger, then benchmark the overhead against raw driver calls. Studying how Kysely, Drizzle, Exposed and Dapper make their trade-offs will sharpen your own design.",
    difficulty: "INTERMEDIATE",
    estimatedHours: 12,
    popularity: 0.55,
    tags: ["backend", "databases", "devtools"],
    languages: ["typescript", "kotlin", "python", "csharp"],
    concepts: ["type-level programming", "parameterised SQL", "builder APIs", "join semantics and nullability", "connection handling"],
  },
];
