import type { SeedProject } from "../types";

export const DATA_PROJECTS: SeedProject[] = [
  {
    slug: "create-a-local-search-engine",
    title: "Create a local search engine",
    summary: "Index your documents with an inverted index, rank with BM25 and serve results in milliseconds.",
    description:
      "Tokenise and normalise documents (lowercasing, stemming, stop words), build an inverted index from term to posting list with positions, and answer queries by intersecting postings and ranking with TF-IDF and then BM25. Index Wikipedia abstracts or your own notes and watch full-text search over hundreds of thousands of documents return in a few milliseconds.\n\nThen build the features that make search feel good: phrase queries with positions, prefix and fuzzy matching, snippets with highlighted terms, faceting, and index compression with variable-byte or delta encoding. Persist the index to disk in segments and support incremental updates. Evaluate ranking quality on a handful of hand-labelled queries. It is the heart of Lucene, Elasticsearch and Meilisearch in miniature.",
    difficulty: "INTERMEDIATE",
    estimatedHours: 12,
    popularity: 0.75,
    tags: ["information-retrieval", "data-engineering", "algorithms"],
    languages: ["rust", "go", "python", "typescript"],
    concepts: ["tokenisation and stemming", "inverted indexes and posting lists", "TF-IDF and BM25 ranking", "phrase and fuzzy queries", "index compression"],
    sourceUrl: "https://artem.krylysov.com/blog/2020/07/28/lets-build-a-full-text-search-engine/",
  },
  {
    slug: "stream-processing-engine",
    title: "Build a stream-processing engine",
    summary: "Process unbounded event streams with windows, watermarks, stateful operators and exactly-once checkpoints.",
    description:
      "Batch systems assume all the data is there; a stream processor must decide when a window is complete while events are still arriving late. Build an engine with sources, map/filter/keyBy operators, tumbling and sliding windows keyed by event time, watermarks that track lateness, and a sink. Feed it a simulated clickstream with out-of-order timestamps and watch aggregations settle correctly.\n\nThen add stateful operators with a local state store, periodic checkpoints so a crash can resume without double counting, and a small dataflow DSL. Measure throughput and latency, and study how Flink and Kafka Streams handle the same problems. Windows and watermarks are the concepts that separate people who have built streaming systems from those who have only used them.",
    difficulty: "ADVANCED",
    estimatedHours: 20,
    popularity: 0.5,
    tags: ["data-engineering", "distributed-systems"],
    languages: ["java", "kotlin", "go", "rust"],
    concepts: ["event time vs processing time", "windows and watermarks", "stateful operators", "checkpointing and exactly-once", "dataflow DSL design"],
  },
  {
    slug: "dag-workflow-scheduler",
    title: "Build a DAG workflow scheduler",
    summary: "Define data pipelines as dependency graphs, run them on a schedule with retries and a status dashboard.",
    description:
      "Describe a workflow as tasks with dependencies, validate that the graph is acyclic, and run tasks in topological order with a configurable level of parallelism. Add cron-style scheduling, per-task retries with backoff, timeouts, and persistence so runs survive a restart and can be resumed from the failed task. Log output per task so debugging a 3 a.m. failure is painless.\n\nA small web dashboard showing DAG structure, run history and task durations turns it into a tool people would use. Then explore backfills for past dates, parameterised runs, sensors that wait for a file or an API, and executing tasks in isolated processes or containers. It is Airflow's core, and building it clarifies why orchestration is its own discipline.",
    difficulty: "INTERMEDIATE",
    estimatedHours: 12,
    popularity: 0.55,
    tags: ["data-engineering", "automation", "backend"],
    languages: ["python", "go", "typescript"],
    concepts: ["DAG validation and topological execution", "cron scheduling", "retries and timeouts", "run persistence and resumption", "operational dashboards"],
    sourceUrl: "https://airflow.apache.org/",
  },
  {
    slug: "read-parquet-files-from-scratch",
    title: "Read Parquet files from scratch",
    summary: "Parse the columnar Parquet format — footer, row groups, pages, encodings — and see why analytics engines love it.",
    description:
      "Parquet stores data by column: a footer describes the schema and row groups, each column chunk is a sequence of pages, and values are encoded with dictionaries, run-length and bit-packing, and compressed. Write a reader that parses the Thrift-encoded metadata, decodes plain and dictionary-encoded columns, and reconstructs rows or, better, hands back columns directly.\n\nThen exploit the format's strengths: read only the columns a query needs, skip row groups using min/max statistics, and process values in vectorised batches. Compare scan speed against CSV. Understanding Parquet from the bytes up explains a lot about DuckDB, Spark and modern data lakes.",
    difficulty: "INTERMEDIATE",
    estimatedHours: 10,
    popularity: 0.4,
    tags: ["data-engineering", "databases", "systems"],
    languages: ["rust", "python", "go", "java"],
    concepts: ["columnar layouts", "Thrift metadata parsing", "dictionary and RLE/bit-packed encodings", "predicate pushdown with statistics", "vectorised reads"],
    sourceUrl: "https://parquet.apache.org/docs/file-format/",
  },
  {
    slug: "jq-style-json-query-language",
    title: "Build a jq-style JSON query language",
    summary: "Design and implement a small language for filtering and transforming JSON streams from the command line.",
    description:
      "jq is a tiny functional language where every expression is a filter from a JSON value to a stream of values. Implement the parser and evaluator for the essentials — path expressions, iteration with .[], pipes, object construction, arithmetic and comparison, select, map and reduce — and stream input so huge NDJSON files process line by line.\n\nThe design questions are the fun part: how do generators backtrack, how do you report errors with positions, how do you make it fast? Add a formatter with colour, a debugger that shows intermediate values, and a test suite ported from jq's manual. You will end up with a tool you use daily and a much deeper understanding of interpreters.",
    difficulty: "INTERMEDIATE",
    estimatedHours: 8,
    popularity: 0.5,
    tags: ["cli", "programming-languages", "data-engineering"],
    languages: ["rust", "go", "typescript", "python"],
    concepts: ["filter-based language design", "generators and backtracking", "streaming JSON parsing", "error reporting", "CLI ergonomics"],
    sourceUrl: "https://jqlang.github.io/jq/",
  },
  {
    slug: "build-a-web-crawler",
    title: "Build a polite, parallel web crawler",
    summary: "Fetch and parse pages concurrently, respect robots.txt and rate limits, and store a link graph you can analyse.",
    description:
      "Start from a seed URL, fetch pages with a bounded pool of workers, extract links, normalise and deduplicate URLs, and enqueue new ones. Politeness is not optional: obey robots.txt, limit requests per host, identify yourself with a user agent, and back off on errors. Persist the frontier and the visited set so a crawl can pause and resume.\n\nStore the pages and the link graph, then do something with them: compute PageRank, feed the text into your own search engine, or detect broken links across your own site. Handle traps (calendar pages, infinite redirects), content-type filtering, and canonical URLs. It is a compact, real-world concurrency and networking exercise.",
    difficulty: "INTERMEDIATE",
    estimatedHours: 8,
    popularity: 0.6,
    tags: ["information-retrieval", "networking", "data-engineering"],
    languages: ["go", "python", "rust"],
    concepts: ["URL frontier and deduplication", "robots.txt and politeness", "bounded concurrency", "link graphs and PageRank", "resumable crawls"],
  },
  {
    slug: "typeahead-autocomplete-service",
    title: "Build a typeahead autocomplete service",
    summary: "Serve ranked prefix suggestions in under a millisecond with a trie, popularity scores and typo tolerance.",
    description:
      "Load a dictionary of terms with popularity counts (city names, product titles, search logs), build a trie or a sorted array with binary search, and answer prefix queries with the top-k results ranked by score. Precomputing the top-k at each trie node makes queries constant time. Serve it over HTTP and wire it to an input box that debounces requests.\n\nThen add fuzzy matching within an edit distance for typos, personalisation that boosts a user's recent choices, multi-word matching, and hot updates without downtime. Measure p99 latency under load and memory per term. It is a small system that shows how much data-structure choice matters for user experience.",
    difficulty: "BEGINNER",
    estimatedHours: 4,
    popularity: 0.5,
    tags: ["information-retrieval", "data-structures", "backend"],
    languages: ["typescript", "go", "rust", "java"],
    concepts: ["tries and prefix search", "top-k ranking", "edit-distance matching", "debouncing and latency budgets", "hot index reloads"],
  },
  {
    slug: "change-data-capture-pipeline",
    title: "Build a change-data-capture pipeline",
    summary: "Stream every insert, update and delete out of PostgreSQL via logical replication into a log and downstream consumers.",
    description:
      "Instead of polling tables, subscribe to the database's own change stream: create a logical replication slot, decode the output plugin's messages (pgoutput or wal2json), and turn them into ordered change events with before and after images. Write them to a log (your own broker or files), and build a consumer that maintains a materialised view or a search index in near real time.\n\nHandle the hard parts: initial snapshots consistent with the stream position, schema changes mid-stream, exactly-once delivery via offsets, and slot management so the database's WAL does not grow forever if your consumer dies. It is the design of Debezium, and building it teaches replication internals and the realities of keeping systems in sync.",
    difficulty: "ADVANCED",
    estimatedHours: 16,
    popularity: 0.35,
    tags: ["data-engineering", "databases", "distributed-systems"],
    languages: ["go", "java", "rust"],
    concepts: ["logical replication and slots", "WAL decoding", "consistent snapshots", "schema evolution", "offset management"],
    sourceUrl: "https://debezium.io/",
  },
];
