import type { SeedProject } from "../types";

export const DEVTOOLS_PROJECTS: SeedProject[] = [
  {
    slug: "build-a-git-clone",
    title: "Build a Git-like version-control system",
    summary: "Implement content-addressed blobs, trees and commits, then staging, branching, diffing and merging.",
    description:
      "Git's object model is tiny: blobs hold file contents, trees hold directory listings, commits point to a tree and parents, and everything is named by the SHA-1 of its zlib-compressed content. Implement init, hash-object, cat-file, add (a staging index), commit, log and checkout, writing objects in Git's real format so the real git can read your repository. That compatibility is a wonderful correctness check.\n\nThen build the algorithms: three-way merge with conflict markers, a diff of trees, branches and HEAD, packfiles if you are brave, and a push/pull over HTTP to a remote you also write. Reading the Git Internals chapter alongside will make you a better Git user forever.",
    difficulty: "INTERMEDIATE",
    estimatedHours: 16,
    popularity: 0.85,
    tags: ["devtools", "systems", "cli", "data-structures"],
    languages: ["rust", "go", "python", "c"],
    concepts: ["content-addressed storage", "Merkle trees (blobs, trees, commits)", "the staging index", "three-way merge", "zlib and binary formats"],
    sourceUrl: "https://git-scm.com/book/en/v2/Git-Internals-Plumbing-and-Porcelain",
  },
  {
    slug: "create-a-toy-compiler",
    title: "Create a toy compiler that emits real assembly",
    summary: "Compile a small C-like language to x86-64 or ARM assembly, one language feature at a time, and run the binaries.",
    description:
      "Start with a program that returns an integer: lex it, parse it into an AST, and emit assembly that the system assembler and linker turn into an executable. Then add unary and binary operators, local variables with stack slots, if/else and loops, functions with the platform calling convention, and pointers. Each step is small, and each produces a real binary you can run and debug with gdb.\n\nWith the front end working, learn what compilers do in the middle: an intermediate representation, constant folding, dead-code elimination, register allocation by linear scan or graph colouring, and a peephole optimiser. Compare your output with clang -O0 and -O2 to see what you are missing. Nora Sandler's series is a proven incremental path.",
    difficulty: "ADVANCED",
    estimatedHours: 40,
    popularity: 0.8,
    tags: ["compilers", "programming-languages", "systems"],
    languages: ["c", "rust", "go", "zig"],
    concepts: ["lexing and recursive-descent parsing", "abstract syntax trees", "code generation and calling conventions", "intermediate representations", "register allocation"],
    sourceUrl: "https://norasandler.com/2017/11/29/Write-a-Compiler.html",
  },
  {
    slug: "build-a-tiny-programming-language",
    title: "Build a tiny programming language",
    summary: "Design a language and implement it twice: a tree-walking interpreter, then a bytecode compiler and VM.",
    description:
      "Design a small dynamically typed language with variables, functions, closures and classes, and implement a scanner, a Pratt parser that handles precedence elegantly, and a tree-walking interpreter with lexical scoping and proper closures. Then implement it again as a single-pass compiler to bytecode running on a stack-based virtual machine, and watch it get an order of magnitude faster.\n\nCrafting Interpreters walks exactly this road and is one of the best programming books ever written. Along the way you will implement environments, resolution of variables, garbage collection, string interning, hash tables and error reporting with line numbers. Finish with a standard library and a REPL, and write a real program in your language.",
    difficulty: "INTERMEDIATE",
    estimatedHours: 25,
    popularity: 0.85,
    tags: ["programming-languages", "compilers"],
    languages: ["typescript", "rust", "go", "java", "c"],
    concepts: ["scanning and Pratt parsing", "closures and lexical scoping", "tree-walking interpretation", "bytecode compilation", "stack-based virtual machines"],
    sourceUrl: "https://craftinginterpreters.com/",
  },
  {
    slug: "write-a-lisp-interpreter",
    title: "Write a Lisp interpreter",
    summary: "Implement a Scheme-like Lisp in an evening — reader, eval, environments, lambdas and macros.",
    description:
      "Lisp's syntax is its data structure, which makes the reader trivial and eval famously short: symbols look up in an environment, lists apply their head to their evaluated arguments, and a handful of special forms (quote, if, define, lambda) do the rest. In a couple of hundred lines you have closures, recursion and higher-order functions running.\n\nThen keep going as far as you like: tail-call optimisation so loops do not blow the stack, macros with quasiquote, a proper numeric tower, strings and I/O, error handling with stack traces, and a REPL with history. The Make-a-Lisp project provides a step-by-step guide with tests in dozens of languages, so you can do this in whatever language you want to learn better.",
    difficulty: "BEGINNER",
    estimatedHours: 5,
    popularity: 0.65,
    tags: ["programming-languages", "compilers"],
    languages: ["python", "typescript", "rust", "go", "c"],
    concepts: ["s-expression parsing", "eval/apply", "environments and closures", "special forms and macros", "tail-call optimisation"],
    sourceUrl: "https://github.com/kanaka/mal",
  },
  {
    slug: "build-a-regex-engine",
    title: "Build a regular-expression engine",
    summary: "Parse patterns into an AST, compile to an NFA and simulate it — then add DFA caching and captures.",
    description:
      "Parse a regex into a syntax tree (concatenation, alternation, repetition, character classes), compile it into a nondeterministic finite automaton with Thompson's construction, and match by simulating sets of NFA states over the input. That approach guarantees linear-time matching, unlike the backtracking engines in most languages, which is a story worth understanding.\n\nThen add anchors, capture groups (via Pike's VM), lazy quantifiers, Unicode classes, and on-the-fly DFA construction with a state cache for speed. Benchmark against your language's built-in engine on pathological patterns like (a*)*b and see yours win. Russ Cox's articles are the definitive guide.",
    difficulty: "INTERMEDIATE",
    estimatedHours: 8,
    popularity: 0.6,
    tags: ["compilers", "algorithms", "programming-languages"],
    languages: ["rust", "go", "python", "typescript", "c"],
    concepts: ["regex parsing", "Thompson NFA construction", "NFA simulation and DFA caching", "capture groups with Pike's VM", "catastrophic backtracking"],
    sourceUrl: "https://swtch.com/~rsc/regexp/regexp1.html",
  },
  {
    slug: "build-a-terminal-ui-framework",
    title: "Build a terminal UI framework",
    summary: "Create a component model, layout engine and renderer for rich terminal apps, with a diffing screen buffer.",
    description:
      "Put the terminal into raw mode, read key and mouse events, and draw into an off-screen cell buffer that you diff against the previous frame so only changed cells are written — the same idea as a virtual DOM. Add a layout system (flexbox-like rows and columns with constraints), widgets (text, list, table, input, progress), focus management and styling with colours and attributes.\n\nDesign the application model deliberately: an Elm-style update/view loop (as in Bubble Tea) or a React-like component tree (as in Ink). Handle resize events, Unicode width, and terminals with different capabilities. Then build a real app on it — a file manager, a log viewer — because that is what shakes out the API.",
    difficulty: "INTERMEDIATE",
    estimatedHours: 14,
    popularity: 0.55,
    tags: ["terminal", "devtools", "frontend"],
    languages: ["rust", "go", "typescript", "python"],
    concepts: ["raw mode and escape sequences", "screen buffer diffing", "layout algorithms", "event loops and focus", "application architecture (Elm/React style)"],
    sourceUrl: "https://github.com/charmbracelet/bubbletea",
  },
  {
    slug: "write-a-terminal-text-editor",
    title: "Write a terminal text editor",
    summary: "Build a small editor with raw-mode input, a text buffer, scrolling, search and syntax highlighting.",
    description:
      "Enter raw mode, read keypresses byte by byte (including escape sequences for arrows), and render rows of text with a status bar using terminal escape codes. Add cursor movement, insertion and deletion, saving, horizontal and vertical scrolling, incremental search and syntax highlighting for one language. The kilo tutorial does all of this in about a thousand lines of C, and it is a joy.\n\nThen choose your own adventure: a rope or piece table so large files stay fast, undo/redo, multiple buffers and splits, a command mode, or a plugin system with a scripting language. Editing your editor's source code in your editor is the moment it becomes real.",
    difficulty: "INTERMEDIATE",
    estimatedHours: 10,
    popularity: 0.75,
    tags: ["terminal", "devtools", "systems"],
    languages: ["c", "rust", "zig", "go"],
    concepts: ["terminal raw mode", "escape-sequence rendering", "text buffer data structures", "incremental search", "syntax highlighting"],
    sourceUrl: "https://viewsourcecode.org/snaptoken/kilo/",
  },
  {
    slug: "write-a-json-parser",
    title: "Write a JSON parser and pretty-printer",
    summary: "Hand-write a recursive-descent JSON parser with precise error messages, then a formatter and a query flag.",
    description:
      "JSON's grammar fits on one page, which makes it the perfect first parser: a tokenizer for strings (with escapes and Unicode), numbers, literals and punctuation, and a recursive-descent parser for objects and arrays. Produce error messages with line and column, and run the parser against the official test suite to find the edge cases you missed — there are more than you think.\n\nThen add a pretty-printer with stable key ordering, a streaming mode for huge files, and a tiny query flag (like a mini jq) to extract paths. Benchmark against your language's built-in parser. It is a two-hour project that quietly teaches everything a parser needs.",
    difficulty: "BEGINNER",
    estimatedHours: 2,
    popularity: 0.6,
    tags: ["compilers", "algorithms", "cli"],
    languages: ["typescript", "python", "rust", "go", "c"],
    concepts: ["tokenising", "recursive descent", "error reporting with positions", "Unicode escapes", "streaming parsing"],
  },
  {
    slug: "build-a-build-system",
    title: "Build a build system with incremental rebuilds",
    summary: "Model targets and dependencies as a graph, rebuild only what changed, and run independent steps in parallel.",
    description:
      "A build system reads rules describing how outputs depend on inputs and commands, builds a directed acyclic graph, and runs commands in topological order. Add timestamps or content hashes so unchanged targets are skipped, parallel execution bounded by CPU count, and a dry-run flag. Use it to build a real multi-file C or TypeScript project.\n\nThe interesting features are the ones that make Make, Ninja and Bazel differ: dynamic dependencies discovered while compiling (header files), a content-addressed cache so identical inputs are never rebuilt twice, sandboxed commands, and clear explanations of why a target was rebuilt. Detecting cycles and giving good errors is a nice touch.",
    difficulty: "INTERMEDIATE",
    estimatedHours: 10,
    popularity: 0.45,
    tags: ["devtools", "cli", "algorithms"],
    languages: ["go", "rust", "python", "typescript"],
    concepts: ["dependency graphs and topological sort", "incremental invalidation", "parallel scheduling", "content hashing", "cycle detection"],
  },
  {
    slug: "build-a-language-server",
    title: "Build a language server",
    summary: "Give a small language editor superpowers — diagnostics, completion, go-to-definition — via the Language Server Protocol.",
    description:
      "The Language Server Protocol lets one server provide editor features to VS Code, Neovim and others. Implement the JSON-RPC transport, initialisation handshake and document synchronisation, then wire in a parser for a small language (your own, or something simple like a config format) to publish diagnostics as the user types. Seeing red squiggles from your own analyser in a real editor is very motivating.\n\nThen add semantic features: symbol tables for go-to-definition and find-references, completion with context, hover with type information, rename, and formatting. Incremental parsing keeps it fast on large files. It is a practical project that teaches how modern developer tooling is structured.",
    difficulty: "ADVANCED",
    estimatedHours: 20,
    popularity: 0.5,
    tags: ["devtools", "compilers", "programming-languages"],
    languages: ["typescript", "rust", "go"],
    concepts: ["JSON-RPC and the LSP lifecycle", "diagnostics publishing", "symbol tables and scopes", "completion and hover", "incremental parsing"],
    sourceUrl: "https://microsoft.github.io/language-server-protocol/",
  },
  {
    slug: "build-a-javascript-bundler",
    title: "Build a JavaScript bundler",
    summary: "Parse modules, resolve imports into a graph, and emit a single file with scope hoisting and tree shaking.",
    description:
      "Start from an entry file, parse it (with your own parser or an existing one), find its import statements, resolve them with Node's algorithm (relative paths, node_modules, package.json fields), and recurse to build a module graph. Then emit a bundle: wrap each module in a function and provide a tiny runtime require, and the browser can run it. That is what Browserify did, and it is a satisfying first milestone.\n\nNext, implement what modern bundlers do: scope hoisting to concatenate modules into one scope, tree shaking based on which exports are actually used, code splitting into chunks for dynamic imports, source maps, and a watch mode with incremental rebuilds. Benchmarking against esbuild will humble and inspire you.",
    difficulty: "INTERMEDIATE",
    estimatedHours: 12,
    popularity: 0.55,
    tags: ["devtools", "compilers", "web"],
    languages: ["typescript", "rust", "go"],
    concepts: ["module resolution", "dependency graphs", "scope hoisting", "tree shaking", "source maps"],
  },
  {
    slug: "write-a-garbage-collector",
    title: "Write a garbage collector for a toy VM",
    summary: "Implement mark-and-sweep, then a copying collector, and measure pause times on a small object-heavy interpreter.",
    description:
      "Give a tiny virtual machine an object heap and a stack of roots, then write a mark-and-sweep collector: mark everything reachable from the roots, sweep the rest onto a free list. It fits in a hundred lines and instantly makes 'reachability' concrete. Add allocation triggers, statistics and a stress mode that collects on every allocation to flush out bugs where a live object was not rooted.\n\nThen implement a semi-space copying collector with Cheney's algorithm to see the trade-off between fragmentation and memory use, and add generations if you enjoy it. Instrument pause times and throughput under a workload, and compare. Bob Nystrom's 'Baby's First Garbage Collector' is a perfect starting point.",
    difficulty: "ADVANCED",
    estimatedHours: 14,
    popularity: 0.5,
    tags: ["programming-languages", "systems", "compilers"],
    languages: ["c", "rust", "zig"],
    concepts: ["roots and reachability", "mark-and-sweep", "copying collection (Cheney)", "generational hypothesis", "GC stress testing"],
    sourceUrl: "https://journal.stuffwithstuff.com/2013/12/08/babys-first-garbage-collector/",
  },
  {
    slug: "implement-diff-with-myers-algorithm",
    title: "Implement diff with the Myers algorithm",
    summary: "Compute minimal edit scripts between files and print unified diffs identical to the real diff tool.",
    description:
      "The diff you read every day is the shortest edit script between two sequences, and Myers' algorithm finds it with an elegant search over an edit graph. Implement it for lines, then produce unified-diff output with hunks and context that matches GNU diff byte for byte on your test files. Then add word-level and character-level diffs for highlighting within lines.\n\nExplore the refinements that make diffs readable: the patience and histogram heuristics that Git uses, indentation-aware slider heuristics, and detecting moved blocks. Wrap it in a CLI with colour output and a side-by-side mode. It is a small algorithm with a huge daily audience.",
    difficulty: "BEGINNER",
    estimatedHours: 4,
    popularity: 0.5,
    tags: ["algorithms", "devtools", "cli"],
    languages: ["python", "typescript", "rust", "go"],
    concepts: ["edit graphs and shortest paths", "Myers' algorithm", "unified diff format", "patience/histogram heuristics", "in-line highlighting"],
    sourceUrl: "https://blog.jcoglan.com/2017/02/12/the-myers-diff-algorithm-part-1/",
  },
  {
    slug: "stack-based-bytecode-vm",
    title: "Build a stack-based bytecode virtual machine",
    summary: "Design an instruction set, write an assembler for it, and execute programs with a fast dispatch loop.",
    description:
      "Define a compact instruction set — push, pop, arithmetic, comparisons, jumps, call and return — with a binary encoding, and write an assembler that turns readable mnemonics into bytecode. Then the VM: a fetch-decode-execute loop over an operand stack with call frames for functions. Run a Fibonacci benchmark and you have a baseline to optimise.\n\nOptimisation is the fun part: computed goto or threaded dispatch, superinstructions, constant pools, and eventually a register-based redesign to compare. Add a debugger that single-steps and shows the stack, and a disassembler. Everything you learn here transfers directly to understanding the JVM, CPython and WebAssembly.",
    difficulty: "INTERMEDIATE",
    estimatedHours: 12,
    popularity: 0.6,
    tags: ["programming-languages", "systems", "compilers"],
    languages: ["c", "rust", "zig", "go"],
    concepts: ["instruction set design", "bytecode encoding", "dispatch loops", "call frames", "profiling and optimisation"],
  },
  {
    slug: "hindley-milner-type-inference",
    title: "Implement Hindley–Milner type inference",
    summary: "Add a type checker to a small functional language that infers polymorphic types without annotations.",
    description:
      "Hindley–Milner is the algorithm that lets ML, OCaml and Haskell infer types like (a -> b) -> [a] -> [b] with no annotations. Implement it for a small lambda calculus with let: generate fresh type variables, unify types while collecting substitutions, and generalise let-bound variables into type schemes. Algorithm W is compact, and watching it infer the type of map is a genuine thrill.\n\nThen extend the language with tuples, algebraic data types and pattern matching, add good error messages that show where unification failed, and explore let-polymorphism's limits (the value restriction) and extensions such as type classes or row polymorphism. It is a deep, satisfying project for anyone curious about how type checkers think.",
    difficulty: "ADVANCED",
    estimatedHours: 16,
    popularity: 0.4,
    tags: ["programming-languages", "compilers", "algorithms"],
    languages: ["rust", "typescript", "python"],
    concepts: ["type variables and substitution", "unification", "generalisation and instantiation", "type schemes", "algebraic data types"],
    sourceUrl: "https://en.wikipedia.org/wiki/Hindley%E2%80%93Milner_type_system",
  },
];
