import type { SeedProject } from "../types";

export const DISTRIBUTED_PROJECTS: SeedProject[] = [
  {
    slug: "implement-raft-consensus",
    title: "Implement Raft consensus",
    summary: "Build a replicated log with leader election, log replication and safety proofs you can test.",
    description:
      "Raft was designed to be understandable, and implementing it is the best way to learn how replicated state machines work. Start with leader election: randomised timeouts, RequestVote RPCs, terms. Then log replication with AppendEntries, commit indexes and the consistency check that forces followers to converge with the leader. Finally, apply committed entries to a state machine — a key-value store is the traditional choice.\n\nThe real work is testing. Build a simulated network that can partition nodes, drop and reorder messages and crash servers, then run thousands of randomised scenarios checking that no two leaders exist in one term and that committed entries are never lost. Add snapshots and log compaction, membership changes, and linearisable reads. Every step is precisely specified in the paper.",
    difficulty: "ADVANCED",
    estimatedHours: 40,
    popularity: 0.75,
    tags: ["distributed-systems", "systems", "networking"],
    languages: ["go", "rust", "java"],
    concepts: ["leader election", "log replication and commit rules", "replicated state machines", "network simulation and fault injection", "snapshots and compaction"],
    sourceUrl: "https://raft.github.io/",
  },
  {
    slug: "distributed-task-queue",
    title: "Build a distributed task queue",
    summary: "Write a job system where producers enqueue work, workers pull it, and failures retry with backoff.",
    description:
      "Producers push jobs (a name, a payload, options) to a queue; worker processes claim jobs, execute them and acknowledge success. Use a database table or your own broker as the queue and get the semantics right: at-least-once delivery, visibility timeouts so a crashed worker's job is reclaimed, idempotency keys, priorities and scheduled jobs that become visible in the future.\n\nThen build the operational layer: retries with exponential backoff and jitter, dead-letter queues, per-queue concurrency limits, graceful worker shutdown that finishes in-flight jobs, and a small dashboard showing throughput and failures. Studying how Celery, Sidekiq and BullMQ solve the same problems will help you decide what to include.",
    difficulty: "INTERMEDIATE",
    estimatedHours: 16,
    popularity: 0.7,
    tags: ["distributed-systems", "backend", "systems"],
    languages: ["go", "python", "typescript", "rust"],
    concepts: ["at-least-once delivery", "visibility timeouts", "idempotency", "backoff and dead-letter queues", "worker lifecycle"],
    sourceUrl: "https://docs.celeryq.dev/",
  },
  {
    slug: "implement-a-message-broker",
    title: "Implement a message broker",
    summary: "Build a log-based broker with topics, partitions, consumer groups and durable offsets.",
    description:
      "Model each topic as a set of partitions, and each partition as an append-only log on disk with an index from offset to file position. Producers append records; consumers read from an offset they control. That single idea — the log as the primary abstraction — is what makes Kafka-style brokers both simple and powerful. Implement segment files, retention by size or time, and batched, length-prefixed records with checksums.\n\nThen add consumer groups: assign partitions across group members, commit offsets, rebalance when members join or leave, and detect dead consumers with heartbeats. Wire protocol design, back-pressure and replication across brokers are natural next steps. Benchmark producer throughput and end-to-end latency to see how batching changes everything.",
    difficulty: "ADVANCED",
    estimatedHours: 30,
    popularity: 0.65,
    tags: ["distributed-systems", "systems", "backend", "networking"],
    languages: ["go", "rust", "java", "kotlin"],
    concepts: ["append-only log segments", "offset indexes", "consumer groups and rebalancing", "retention policies", "batching and back-pressure"],
    sourceUrl: "https://kafka.apache.org/",
  },
  {
    slug: "distributed-key-value-store",
    title: "Build a distributed key-value store",
    summary: "Shard keys across nodes with consistent hashing, replicate them, and handle nodes leaving and joining.",
    description:
      "Run several nodes, place them on a hash ring with virtual nodes, and route each key to its owner and N-1 successors for replication. Clients can talk to any node, which forwards requests, and reads and writes succeed when a quorum responds. When a node joins or leaves, only a fraction of keys move — the whole point of consistent hashing.\n\nThe interesting failures come next: two replicas disagree after a partition (use vector clocks or last-writer-wins and expose conflicts), a node comes back stale (hinted handoff and anti-entropy with Merkle trees), and hot keys overload one owner. This is a hands-on tour through the Dynamo paper, and every mechanism becomes obvious once you have hit the problem it solves.",
    difficulty: "ADVANCED",
    estimatedHours: 30,
    popularity: 0.6,
    tags: ["distributed-systems", "databases", "networking"],
    languages: ["go", "rust", "java"],
    concepts: ["consistent hashing", "quorum reads and writes", "replication and hinted handoff", "conflict resolution", "anti-entropy with Merkle trees"],
    sourceUrl: "https://www.allthingsdistributed.com/files/amazon-dynamo-sosp2007.pdf",
  },
  {
    slug: "gossip-membership-protocol",
    title: "Implement gossip-based cluster membership",
    summary: "Build a SWIM-style protocol where nodes discover each other, detect failures and spread state epidemically.",
    description:
      "Every node periodically pings a random peer; if the ping fails, it asks a few other nodes to ping on its behalf before declaring the peer suspect and eventually dead. Membership updates piggyback on those messages and spread through the cluster in logarithmic time. That is SWIM, the protocol under Consul, memberlist and many service meshes.\n\nImplement the failure detector, the dissemination component with per-update counters, incarnation numbers so a falsely-accused node can refute its own death, and a simple key-value metadata layer on top. Then run a hundred simulated nodes, inject packet loss and partitions, and measure detection time and false positive rates against the paper's predictions.",
    difficulty: "INTERMEDIATE",
    estimatedHours: 12,
    popularity: 0.4,
    tags: ["distributed-systems", "networking"],
    languages: ["go", "rust", "python"],
    concepts: ["failure detection", "epidemic dissemination", "incarnation numbers and refutation", "membership lists", "simulation under packet loss"],
  },
  {
    slug: "crdt-library-and-collaborative-demo",
    title: "Build a CRDT library and a collaborative demo",
    summary: "Implement counters, sets and a sequence CRDT, then sync two browsers with no central server logic.",
    description:
      "Conflict-free replicated data types let replicas accept writes independently and converge without coordination. Start with the easy ones — grow-only counter, PN-counter, LWW-register, OR-set — and write property tests proving that merging in any order gives the same state. Then implement a sequence CRDT (RGA or a simplified YATA/Yjs approach) with unique per-character identifiers so concurrent edits to a text interleave sensibly.\n\nPut it into a demo: two browser tabs editing the same document over WebSockets or WebRTC, with the network deliberately delayed so you can watch conflicts resolve. Explore tombstone garbage collection, delta-state syncing to reduce bandwidth, and undo. You will understand exactly why tools like Figma and Notion can feel local-first.",
    difficulty: "INTERMEDIATE",
    estimatedHours: 14,
    popularity: 0.55,
    tags: ["distributed-systems", "data-structures", "web"],
    languages: ["typescript", "rust", "go"],
    concepts: ["convergence and commutativity", "state-based vs operation-based CRDTs", "sequence CRDT identifiers", "property-based testing", "delta synchronisation"],
    sourceUrl: "https://crdt.tech/",
  },
  {
    slug: "mapreduce-framework",
    title: "Build a MapReduce framework",
    summary: "Write a coordinator and workers that run map and reduce tasks over files, with retries when workers die.",
    description:
      "Implement the classic system: a coordinator splits input files into map tasks, workers pull tasks over RPC, map output is partitioned by key into intermediate files, and reduce tasks merge each partition and write results. Run word count and an inverted index over a corpus to prove it works, first in one process, then across many.\n\nThe distributed-systems lessons come from failure. Workers must be able to die at any moment: the coordinator re-assigns timed-out tasks, and output files are written atomically via rename so partial results never leak. Add speculative execution for stragglers, combiners to reduce shuffle volume, and a small progress UI. This is the same lab MIT's 6.824 uses, and for good reason.",
    difficulty: "INTERMEDIATE",
    estimatedHours: 16,
    popularity: 0.55,
    tags: ["distributed-systems", "data-engineering"],
    languages: ["go", "python", "java"],
    concepts: ["task scheduling over RPC", "partitioning by key", "atomic file outputs", "worker failure handling", "stragglers and speculative execution"],
    sourceUrl: "https://research.google/pubs/pub62/",
  },
  {
    slug: "distributed-lock-service",
    title: "Build a distributed lock service",
    summary: "Provide leases and fencing tokens so processes can coordinate safely even when clocks and networks misbehave.",
    description:
      "A lock service hands out time-limited leases on named resources; clients renew leases with heartbeats and lose them if they stop. Implement the server, a client library with automatic renewal, and the essential detail that most homemade locks miss: a monotonically increasing fencing token that downstream systems check so a client that paused (GC, network blip) and lost its lease cannot corrupt data.\n\nThen make the service itself fault-tolerant by putting the state behind your own Raft implementation or a replicated log, and write chaos tests that pause clients, partition the network and skew clocks. The Chubby paper and Martin Kleppmann's essay on distributed locking are ideal companions.",
    difficulty: "INTERMEDIATE",
    estimatedHours: 12,
    popularity: 0.4,
    tags: ["distributed-systems", "systems", "backend"],
    languages: ["go", "rust", "java"],
    concepts: ["leases and heartbeats", "fencing tokens", "clock skew hazards", "client libraries with renewal", "chaos testing"],
    sourceUrl: "https://research.google/pubs/pub27897/",
  },
  {
    slug: "event-sourcing-store",
    title: "Build an event-sourced store with projections",
    summary: "Persist state as an append-only stream of events and rebuild any view by replaying them.",
    description:
      "Instead of storing current state, store every event that ever happened (AccountOpened, MoneyDeposited) in per-aggregate streams with optimistic concurrency on the stream version. Rebuild an aggregate by folding its events, and build read models by projecting events into query-friendly tables that can be rebuilt from scratch at any time.\n\nBuild a small domain (a bank, an inventory, a to-do app), a subscription mechanism that feeds projections in order with checkpoints, and snapshots so long streams load quickly. Then explore the hard parts: schema evolution of old events, idempotent projections, and time-travel debugging where you replay to any past moment. It changes how you think about state.",
    difficulty: "INTERMEDIATE",
    estimatedHours: 12,
    popularity: 0.5,
    tags: ["backend", "distributed-systems", "databases"],
    languages: ["typescript", "csharp", "kotlin", "go"],
    concepts: ["append-only event streams", "optimistic concurrency", "projections and read models", "snapshots", "event schema evolution"],
    sourceUrl: "https://martinfowler.com/eaaDev/EventSourcing.html",
  },
  {
    slug: "vector-clocks-causal-chat",
    title: "Implement vector clocks in a causal-order chat",
    summary: "Build a tiny multi-node chat that delivers messages in causal order using vector clocks.",
    description:
      "In a distributed chat, a reply can arrive before the message it answers. Attach a vector clock to every message, buffer messages whose causal dependencies have not arrived yet, and deliver them only when the clock says it is safe. Watching messages reorder themselves correctly on a deliberately laggy network makes the abstract idea of happens-before concrete.\n\nStart with three simulated nodes in one process, then run them as separate processes over UDP with random delays and drops. Add version-vector comparison to detect concurrent edits of a shared value, and compare vector clocks with Lamport timestamps and hybrid logical clocks. It is a short project that becomes a mental model you will use forever.",
    difficulty: "BEGINNER",
    estimatedHours: 5,
    popularity: 0.35,
    tags: ["distributed-systems", "algorithms"],
    languages: ["python", "typescript", "go"],
    concepts: ["happens-before relation", "vector clocks", "causal delivery buffering", "concurrency detection", "logical vs physical time"],
  },
  {
    slug: "saga-orchestrator",
    title: "Build a saga orchestrator",
    summary: "Coordinate multi-step workflows across services with compensating actions when a step fails.",
    description:
      "When a checkout touches inventory, payment and shipping services, you cannot wrap them in one transaction. A saga runs each step in order and, on failure, executes compensations for the steps already done. Build an orchestrator that persists workflow state, drives steps through HTTP calls or a queue, retries transient failures, and runs compensations in reverse order when a step gives up.\n\nModel workflows declaratively, make every step idempotent so retries are safe, and expose a view of every running and failed saga for operators. Then test it by making downstream services fail randomly and confirming the system always ends in a consistent state. Temporal and AWS Step Functions are the industrial versions of what you are building.",
    difficulty: "INTERMEDIATE",
    estimatedHours: 10,
    popularity: 0.35,
    tags: ["backend", "distributed-systems"],
    languages: ["java", "csharp", "typescript", "go"],
    concepts: ["saga pattern and compensations", "durable workflow state", "idempotent steps", "retry policies", "operator visibility"],
    sourceUrl: "https://microservices.io/patterns/data/saga.html",
  },
];
