import type { SeedProject } from "../types";

export const GAME_PROJECTS: SeedProject[] = [
  {
    slug: "multiplayer-drawing-game",
    title: "Build a multiplayer drawing game",
    summary: "One player draws, everyone else guesses in real time — rooms, turns, scoring and a shared canvas over WebSockets.",
    description:
      "Players join a room, one is chosen to draw a secret word, and their strokes stream to everyone else while guesses arrive in chat. Build the canvas with pointer events, send strokes as compact point batches, and keep the server authoritative for turns, timers and scoring so a modified client cannot cheat. Late joiners need the full drawing so far, which forces you to think about state replay.\n\nThen make it delightful: undo, brush sizes and colours, hints that reveal letters over time, close-guess detection, spectators, reconnection without losing your place, and a lobby with public and private rooms. It touches real-time networking, state synchronisation and interaction design in a project you can play with friends the same evening.",
    difficulty: "INTERMEDIATE",
    estimatedHours: 14,
    popularity: 0.7,
    tags: ["multiplayer", "game-development", "web", "backend"],
    languages: ["typescript"],
    concepts: ["WebSocket rooms and broadcast", "authoritative server state", "canvas stroke streaming", "state replay for late joiners", "reconnection handling"],
  },
  {
    slug: "roguelike-with-procedural-dungeons",
    title: "Build a roguelike with procedural dungeons",
    summary: "Generate dungeons, add field of view, monsters with AI and permadeath in a turn-based grid game.",
    description:
      "Roguelikes are the ideal solo game project because every system is small and self-contained. Generate a dungeon by placing rooms and connecting them with corridors (or with BSP or cellular automata for caves), implement field-of-view with shadowcasting so you only see what your character sees, and add turn-based movement, monsters that path toward you with A* or Dijkstra maps, combat, items and stairs.\n\nThe classic tutorial gets you a playable game quickly; then the design space opens up: an inventory and equipment, status effects, a message log, saving and loading, ASCII or tileset rendering, and procedurally named loot. Balancing the difficulty curve so runs feel fair yet deadly is the real art.",
    difficulty: "INTERMEDIATE",
    estimatedHours: 16,
    popularity: 0.7,
    tags: ["game-development", "procedural-generation", "terminal"],
    languages: ["python", "rust", "typescript", "csharp"],
    concepts: ["dungeon generation", "field of view (shadowcasting)", "turn-based game loops", "pathfinding for AI", "save/load serialisation"],
    sourceUrl: "https://rogueliketutorials.com/",
  },
  {
    slug: "write-a-chess-engine",
    title: "Write a chess engine",
    summary: "Generate legal moves with bitboards, search with alpha-beta and evaluate positions well enough to beat you.",
    description:
      "Represent the board with bitboards, generate pseudo-legal moves with precomputed attack tables (magic bitboards for sliders if you are ambitious), and verify legality by checking for exposed kings. A perft test that counts leaf nodes to a known depth is the essential correctness tool — every engine author has chased a perft mismatch caused by en passant or castling rights.\n\nThen search: negamax with alpha-beta pruning, iterative deepening, a transposition table with Zobrist hashing, move ordering (captures first, killer moves), quiescence search to avoid horizon effects, and a hand-tuned evaluation with piece-square tables. Speak UCI so a chess GUI can play against your engine, and measure its rating in engine tournaments. It is an endlessly deep project.",
    difficulty: "ADVANCED",
    estimatedHours: 30,
    popularity: 0.7,
    tags: ["game-development", "algorithms"],
    languages: ["cpp", "rust", "c", "python"],
    concepts: ["bitboards", "move generation and perft", "alpha-beta search", "transposition tables and Zobrist hashing", "evaluation functions"],
    sourceUrl: "https://www.chessprogramming.org/",
  },
  {
    slug: "entity-component-system-engine",
    title: "Build an entity-component-system game engine",
    summary: "Design a data-oriented ECS core, then a renderer, input, physics and scene loading around it.",
    description:
      "In an ECS, entities are ids, components are plain data stored in dense arrays, and systems iterate over the entities that have particular component combinations. Implement archetype or sparse-set storage, fast queries, and a scheduler that runs systems in order (or in parallel when they touch disjoint components). Cache-friendly iteration is the whole point, so benchmark against an object-oriented design.\n\nBuild the rest of a small engine around it: a 2D renderer with sprite batching, input handling, a fixed-timestep game loop, simple collision, scene serialisation and a tiny asset pipeline. Ship a small game on it — that is the only real test of an engine. Reading Bevy's or flecs' architecture afterwards will make sense of every choice they made.",
    difficulty: "ADVANCED",
    estimatedHours: 30,
    popularity: 0.5,
    tags: ["game-development", "systems"],
    languages: ["rust", "cpp", "csharp", "typescript"],
    concepts: ["data-oriented design", "archetype/sparse-set storage", "system scheduling", "fixed-timestep loops", "sprite batching"],
    sourceUrl: "https://gameprogrammingpatterns.com/",
  },
  {
    slug: "rollback-netcode-prototype",
    title: "Build a rollback netcode fighting-game prototype",
    summary: "Make a two-player game feel lag-free by predicting inputs, rewinding and resimulating when they are wrong.",
    description:
      "Deterministic simulation is the foundation: the same inputs must produce the same state on both machines, which rules out floating-point surprises and unordered iteration. Exchange only inputs between peers, predict the remote player's input as 'same as last frame', and when the real input arrives, roll back to that frame's saved state and resimulate forward. Done right, both players feel local responsiveness at 100 ms of latency.\n\nBuild a tiny fighting or platforming game with fixed-point maths, implement state save/restore, input delay and rollback windows, a simulated network with configurable latency and jitter, and an on-screen graph of rollbacks. GGPO's design documents describe the model your prototype will converge on.",
    difficulty: "ADVANCED",
    estimatedHours: 20,
    popularity: 0.35,
    tags: ["multiplayer", "game-development", "networking"],
    languages: ["typescript", "rust", "csharp"],
    concepts: ["deterministic simulation", "input prediction and rollback", "state snapshots", "fixed-point arithmetic", "network latency simulation"],
    sourceUrl: "https://www.ggpo.net/",
  },
  {
    slug: "tetris-clone",
    title: "Build Tetris with proper rotation and scoring",
    summary: "Implement the tetromino guideline: rotation systems, wall kicks, lock delay, ghost pieces and levels.",
    description:
      "Tetris is small enough to finish and precise enough to teach discipline. Implement the seven tetrominoes, a bag randomiser, gravity that speeds up with levels, line clears with scoring, and the Super Rotation System with wall kicks so pieces rotate the way players expect. Lock delay, hold, ghost piece and next-queue previews are what make it feel like a real game rather than a demo.\n\nRender it with canvas, a terminal, or a game framework, add keyboard handling with DAS/ARR-style repeat, sound effects, and a local high-score table. Then, if you like, write a bot that plays it using a heuristic evaluation of the stack — a fun first taste of game AI.",
    difficulty: "BEGINNER",
    estimatedHours: 4,
    popularity: 0.65,
    tags: ["game-development"],
    languages: ["typescript", "python", "rust", "csharp"],
    concepts: ["game loops and timing", "grid collision", "rotation systems and wall kicks", "input handling with key repeat", "simple game AI"],
  },
  {
    slug: "sudoku-generator-and-solver",
    title: "Build a Sudoku generator and solver",
    summary: "Solve puzzles with constraint propagation and search, then generate unique-solution puzzles by difficulty.",
    description:
      "Solving is a beautiful small algorithm: propagate constraints (eliminate candidates from peers, assign forced values) and search with backtracking when propagation stalls. Peter Norvig's essay shows it in about a hundred lines. Implement it, then measure how many puzzles it solves without any search at all.\n\nGeneration is the more interesting half: fill a grid randomly, remove clues while checking that exactly one solution remains, and rate difficulty by the techniques required (naked singles, hidden pairs, X-wings). Build a small UI with pencil marks and hints that explain the next logical step. It is a compact lesson in constraint satisfaction.",
    difficulty: "BEGINNER",
    estimatedHours: 3,
    popularity: 0.55,
    tags: ["algorithms", "game-development"],
    languages: ["python", "typescript", "rust"],
    concepts: ["constraint propagation", "backtracking search", "uniqueness checking", "difficulty rating", "hint generation"],
    sourceUrl: "https://norvig.com/sudoku.html",
  },
  {
    slug: "text-adventure-engine",
    title: "Build a text adventure engine with its own scripting language",
    summary: "Create an interactive-fiction engine with a world model, a parser for commands and a story format others can write in.",
    description:
      "Model rooms, exits, objects with properties and the player's inventory, then write a command parser that understands 'take the brass lamp', 'go north' and 'unlock door with key' with reasonable forgiveness. The engine reads a story from a data file or a small domain-specific language you design, so writing a new game means writing content, not code.\n\nAdd conditions and triggers (a door that opens when a lever is pulled), save and restore, undo, and a scripting layer for custom behaviour. Publish a short game written in your format. It is a gentle introduction to parsers, interpreters and world modelling with an unusually charming payoff.",
    difficulty: "BEGINNER",
    estimatedHours: 6,
    popularity: 0.45,
    tags: ["game-development", "programming-languages", "terminal"],
    languages: ["python", "typescript", "rust"],
    concepts: ["world modelling", "command parsing", "domain-specific languages", "event triggers", "save/restore"],
  },
  {
    slug: "tower-defense-game",
    title: "Build a tower defense game",
    summary: "Path enemies through a grid with A*, place towers with targeting strategies and balance waves and economy.",
    description:
      "Enemies spawn in waves and walk the shortest path to your base; you place towers that shoot them. Implement grid pathfinding that recomputes when a tower blocks a route (and refuses placements that block it entirely), tower types with different ranges, fire rates and targeting rules (first, strongest, closest), projectiles, and an economy of gold and upgrades.\n\nThe design work — wave composition, cost curves, tower synergies — is as engaging as the code, and a small data-driven config makes iteration fast. Add sprites and animations, sound, a level editor, and flow-field pathfinding when hundreds of enemies make per-unit A* too slow.",
    difficulty: "INTERMEDIATE",
    estimatedHours: 12,
    popularity: 0.5,
    tags: ["game-development", "algorithms"],
    languages: ["typescript", "csharp", "rust"],
    concepts: ["grid pathfinding (A*, flow fields)", "targeting strategies", "game economy balancing", "sprite animation", "data-driven design"],
  },
  {
    slug: "wordle-clone-and-solver",
    title: "Build a Wordle clone and an optimal solver",
    summary: "Recreate the daily word game, then write a solver that picks guesses by expected information gain.",
    description:
      "The game itself is a satisfying afternoon: a keyboard, six rows of tiles, the tricky feedback rule for repeated letters, a daily seed, share-able emoji results and streak statistics stored locally. Get the colouring rule exactly right — most first attempts mishandle duplicates.\n\nThe solver is where it gets interesting: for each candidate guess, compute the distribution of feedback patterns over the remaining possible answers, and choose the guess with the highest entropy. Watch it solve nearly every puzzle in three or four guesses, then explore the trade-off between information gain and guessing a plausible answer. It is a lovely, concrete introduction to information theory.",
    difficulty: "BEGINNER",
    estimatedHours: 3,
    popularity: 0.5,
    tags: ["game-development", "algorithms", "web"],
    languages: ["typescript", "python"],
    concepts: ["game state and feedback rules", "local persistence", "entropy and expected information", "candidate filtering", "solver evaluation"],
  },
];
