import type { SeedProject } from "../types";

export const GRAPHICS_PROJECTS: SeedProject[] = [
  {
    slug: "implement-a-ray-tracer",
    title: "Implement a ray tracer",
    summary: "Render spheres with reflections, refraction and soft shadows by shooting rays through every pixel.",
    description:
      "For each pixel, cast a ray from the camera into the scene, find the nearest intersection, and compute a colour from materials and lights. With a sphere intersection routine, a diffuse material and a sky gradient you get a recognisable image in an hour; add metal and glass materials, depth of field and anti-aliasing and the images become genuinely beautiful. It is the rare project where every step produces a picture you want to show someone.\n\nOnce the basics render, add triangle meshes loaded from OBJ files, a bounding volume hierarchy so complex scenes render in seconds rather than hours, textures, and multithreading. Progressive rendering that refines the image over time makes the tool feel alive. The Ray Tracing in One Weekend series is a superb guide.",
    difficulty: "INTERMEDIATE",
    estimatedHours: 12,
    popularity: 0.88,
    tags: ["graphics"],
    languages: ["cpp", "rust", "c", "python"],
    concepts: ["ray-object intersection", "materials and shading", "recursion and reflection", "anti-aliasing and sampling", "bounding volume hierarchies"],
    sourceUrl: "https://raytracing.github.io/",
  },
  {
    slug: "webgl-fluid-simulation",
    title: "Create a WebGL fluid simulation",
    summary: "Solve the Navier–Stokes equations on the GPU and let users stir colourful smoke with their mouse.",
    description:
      "Implement Jos Stam's stable fluids method entirely in fragment shaders: velocity and dye fields live in textures, and each frame runs advection, diffusion, a pressure solve with Jacobi iterations and a projection step that keeps the flow divergence-free. Pointer movement injects velocity and colour. The result is the mesmerising interactive smoke you have seen in browser demos, and it runs at 60 fps on almost anything.\n\nThe project teaches GPU programming as much as physics: ping-pong framebuffers, floating-point textures, texture formats and precision on mobile, and structuring a multi-pass render pipeline. Add vorticity confinement for crisper swirls, bloom, obstacles in the flow, and touch support, then port it to WebGPU compute shaders if you want to compare.",
    difficulty: "ADVANCED",
    estimatedHours: 20,
    popularity: 0.75,
    tags: ["webgl", "graphics", "simulation", "creative-coding"],
    languages: ["typescript", "glsl"],
    concepts: ["stable fluids (advection, diffusion, projection)", "fragment shaders as compute", "ping-pong framebuffers", "floating-point textures", "multi-pass render pipelines"],
    sourceUrl: "https://www.dgp.toronto.edu/public_user/stam/reality/Research/pdf/GDC03.pdf",
  },
  {
    slug: "software-rasterizer",
    title: "Write a software rasterizer",
    summary: "Draw triangles, textures and lit 3D models pixel by pixel without a GPU, the way OpenGL does inside.",
    description:
      "Start with Bresenham lines, then fill triangles by testing barycentric coordinates over their bounding box. Add a depth buffer, load an OBJ model with UVs and normals, project vertices with model, view and perspective matrices, and shade with a simple lighting model. Watching a textured, lit head appear from your own scanline code demystifies the entire graphics pipeline.\n\nThen implement the parts a GPU does for you: perspective-correct interpolation, clipping against the near plane, back-face culling, normal mapping, shadow mapping and a programmable vertex/fragment shader interface. Optimise with tiling and SIMD if you enjoy performance work. The tinyrenderer course is a compact roadmap.",
    difficulty: "INTERMEDIATE",
    estimatedHours: 14,
    popularity: 0.7,
    tags: ["graphics"],
    languages: ["cpp", "rust", "c", "zig"],
    concepts: ["triangle rasterisation", "depth buffering", "transformation matrices", "perspective-correct interpolation", "shading models"],
    sourceUrl: "https://github.com/ssloy/tinyrenderer",
  },
  {
    slug: "generative-art-playground",
    title: "Create a generative-art playground",
    summary: "Build a canvas sketchbook of algorithmic art — flow fields, noise, recursion — with seeds you can share.",
    description:
      "Set up a canvas, a seeded random number generator and a tiny framework for sketches, then explore: flow fields driven by Perlin noise, recursive subdivision, circle packing, Truchet tiles, random walkers, and colour palettes chosen from photographs. Every sketch is a few dozen lines, and the seed makes each piece reproducible so you can save the ones you love.\n\nAdd export to high-resolution PNG and SVG for printing, a small UI for parameters, and animation via requestAnimationFrame. The deeper skills — composition, controlled randomness, working with colour spaces — transfer to visualisation and UI work. The Nature of Code is the classic companion.",
    difficulty: "BEGINNER",
    estimatedHours: 5,
    popularity: 0.7,
    tags: ["creative-coding", "graphics", "procedural-generation"],
    languages: ["typescript", "javascript", "python"],
    concepts: ["seeded randomness", "noise functions", "canvas drawing APIs", "colour palettes and spaces", "exporting vector and raster art"],
    sourceUrl: "https://natureofcode.com/",
  },
  {
    slug: "live-shader-playground",
    title: "Build a live-coding shader playground",
    summary: "Make a Shadertoy-style editor that compiles GLSL as you type and feeds it time, mouse and textures.",
    description:
      "Render a full-screen quad, compile the fragment shader from an editor pane on every keystroke, and show compile errors inline with line numbers. Provide uniforms for time, resolution and mouse, plus texture channels, and you have a tool that makes shader experimentation instant. Write a handful of shaders yourself — plasma, raymarched spheres, signed-distance-field text — to test it.\n\nThen add multi-pass buffers so shaders can read their previous frame (feedback effects, simulations), a gallery with shareable URLs that encode the code, recording to video, and syntax highlighting. Handling shader compilation off the main thread and debouncing keeps it responsive. It is a small tool with a large creative surface.",
    difficulty: "INTERMEDIATE",
    estimatedHours: 8,
    popularity: 0.6,
    tags: ["webgl", "graphics", "creative-coding", "devtools"],
    languages: ["typescript", "glsl"],
    concepts: ["fragment shaders and uniforms", "GLSL compilation and error handling", "raymarching and SDFs", "multi-pass feedback", "editor UX"],
    sourceUrl: "https://thebookofshaders.com/",
  },
  {
    slug: "procedural-terrain-generator",
    title: "Create a procedural terrain generator",
    summary: "Generate infinite mountains, rivers and biomes from noise and render them as a flyable 3D landscape.",
    description:
      "Layer octaves of Perlin or simplex noise into a heightmap, then shape it: apply curves for plateaus and valleys, run hydraulic erosion to carve realistic river channels, and classify biomes by elevation, moisture and temperature. Render the result as a mesh with vertex colours or textures and fly a camera over it. Chunking and level of detail let the world extend forever.\n\nEvery stage is a tunable knob you can expose in a UI, which makes the project a joy to iterate on. Go further with a minimap, procedurally placed trees and rocks, water with reflections, and a seed system so a world can be regenerated exactly. The techniques transfer directly to games and to data-driven visualisation.",
    difficulty: "INTERMEDIATE",
    estimatedHours: 12,
    popularity: 0.65,
    tags: ["procedural-generation", "graphics", "simulation", "game-development"],
    languages: ["typescript", "rust", "cpp", "glsl"],
    concepts: ["fractal noise", "hydraulic erosion", "biome classification", "mesh generation and chunking", "level of detail"],
    sourceUrl: "https://mrl.cs.nyu.edu/~perlin/noise/",
  },
  {
    slug: "physically-based-path-tracer",
    title: "Build a physically based path tracer",
    summary: "Go beyond a basic ray tracer with Monte Carlo integration, importance sampling and real materials.",
    description:
      "Where a simple ray tracer fakes lighting, a path tracer estimates the rendering equation: bounce rays randomly around the scene, accumulate radiance, and let thousands of samples per pixel converge on the physically correct answer. Implement Lambertian and microfacet BRDFs, area lights, and Russian roulette termination, and watch noise turn into photographs.\n\nThe interesting engineering is variance reduction: importance sampling of BRDFs and lights, multiple importance sampling, stratified and low-discrepancy sampling, and eventually a denoiser. Add a BVH for meshes, environment maps and volumetric scattering. Physically Based Rendering is the reference; even a fraction of it produces stunning images.",
    difficulty: "ADVANCED",
    estimatedHours: 30,
    popularity: 0.55,
    tags: ["graphics", "algorithms"],
    languages: ["cpp", "rust", "glsl"],
    concepts: ["Monte Carlo integration", "BRDFs and the rendering equation", "importance sampling", "multiple importance sampling", "acceleration structures"],
    sourceUrl: "https://pbr-book.org/",
  },
  {
    slug: "2d-physics-engine",
    title: "Write a 2D rigid-body physics engine",
    summary: "Simulate boxes and circles that fall, collide, stack and rest realistically using impulse-based solving.",
    description:
      "Integrate positions and velocities each frame, detect collisions between circles and convex polygons using the separating axis theorem, generate contact points, and resolve them with impulses that account for restitution and friction. Getting a stack of boxes to rest without jittering is the classic milestone — it requires sequential impulses, warm starting and a bit of Baumgarte stabilisation.\n\nAdd broad-phase culling with a spatial hash or sweep-and-prune, joints and springs, sleeping bodies, and a debug renderer showing contacts and normals. Then build a small game or a sandbox on top. Box2D's design and Erin Catto's GDC talks are the definitive references, and after this project you will read them fluently.",
    difficulty: "ADVANCED",
    estimatedHours: 20,
    popularity: 0.6,
    tags: ["simulation", "game-development", "graphics"],
    languages: ["typescript", "cpp", "rust"],
    concepts: ["numerical integration", "separating axis theorem", "contact generation", "impulse-based constraint solving", "broad-phase collision"],
    sourceUrl: "https://box2d.org/",
  },
  {
    slug: "boids-flocking-simulation",
    title: "Simulate flocking with boids",
    summary: "Make hundreds of agents flock with three simple rules, then scale to thousands with spatial hashing.",
    description:
      "Craig Reynolds' boids follow three local rules — separation, alignment and cohesion — and produce startlingly lifelike flocks. Implement the agents, tune the radii and weights with sliders, and add predators, obstacles and wind. Ten thousand boids will bring a naive O(n²) neighbour search to its knees, which is your cue to add a spatial hash grid or quadtree.\n\nRender with canvas or WebGL instancing, add trails and colour by velocity, and export a GIF. It is a short project that teaches emergent behaviour, vector math and the neighbour-search problem that recurs in physics, games and simulation.",
    difficulty: "BEGINNER",
    estimatedHours: 3,
    popularity: 0.55,
    tags: ["simulation", "creative-coding", "algorithms"],
    languages: ["typescript", "python", "rust"],
    concepts: ["steering behaviours", "vector maths", "spatial hashing", "emergent behaviour", "instanced rendering"],
    sourceUrl: "https://www.red3d.com/cwr/boids/",
  },
  {
    slug: "reaction-diffusion-explorer",
    title: "Build a reaction-diffusion pattern explorer",
    summary: "Grow coral, spots and stripes from two chemicals reacting on a grid, running on the GPU with live controls.",
    description:
      "The Gray–Scott model is two coupled equations on a grid; iterate them and organic patterns emerge — mitosis-like blobs, mazes, spots and coral. Implement it on the CPU first to understand it, then move it into a fragment shader with ping-pong textures so a full-screen simulation runs in real time. Expose feed and kill rates as sliders and let people paint chemical with the mouse.\n\nAdd a preset gallery of famous parameter regions, colour mapping, seeding from an image, and export to video. It is a compact introduction to numerical simulation on GPUs and a reliably beautiful result.",
    difficulty: "BEGINNER",
    estimatedHours: 4,
    popularity: 0.4,
    tags: ["creative-coding", "simulation", "webgl"],
    languages: ["typescript", "glsl", "python"],
    concepts: ["Gray–Scott reaction-diffusion", "finite-difference simulation", "GPU ping-pong textures", "parameter exploration UI", "colour mapping"],
    sourceUrl: "https://www.karlsims.com/rd.html",
  },
  {
    slug: "l-system-plant-generator",
    title: "Grow plants with L-systems",
    summary: "Rewrite strings with production rules and interpret them as turtle graphics to draw trees and ferns.",
    description:
      "An L-system rewrites a string repeatedly using rules (F → F[+F]F[-F]F) and a turtle interprets the result: F draws forward, + and - turn, brackets push and pop state. A dozen lines of code produce branching plants; stochastic rules, parametric symbols and 3D turtles produce forests. Implement the rewriting engine, the turtle renderer and a small rule editor.\n\nAnimate growth by interpolating between iterations, add tropism so branches bend toward light, render leaves and flowers, and export SVG. The Algorithmic Beauty of Plants is a free book full of rules to try. It is a delightful way to learn formal grammars.",
    difficulty: "BEGINNER",
    estimatedHours: 4,
    popularity: 0.45,
    tags: ["procedural-generation", "creative-coding", "graphics"],
    languages: ["typescript", "python"],
    concepts: ["formal grammars and rewriting", "turtle graphics", "stochastic and parametric rules", "recursion and branching", "SVG export"],
    sourceUrl: "http://algorithmicbotany.org/papers/#abop",
  },
  {
    slug: "truetype-font-rasterizer",
    title: "Parse TrueType fonts and rasterize glyphs",
    summary: "Read a .ttf file, extract glyph outlines and render anti-aliased text with your own scanline algorithm.",
    description:
      "A TrueType file is a set of binary tables: cmap maps characters to glyph ids, loca and glyf hold quadratic Bézier outlines, hmtx holds advance widths. Parse them, flatten the curves into line segments, and rasterize glyphs with a scanline fill that computes coverage for anti-aliasing. Rendering 'Hello' in a real font from bytes you decoded yourself is a superb moment.\n\nThen tackle the parts that make text hard: the non-zero winding rule for overlapping contours, kerning from the kern or GPOS table, hinting (or deliberately ignoring it), subpixel positioning and a glyph atlas cache for real-time rendering. Signed-distance-field rendering is a natural extension for GPU text.",
    difficulty: "ADVANCED",
    estimatedHours: 20,
    popularity: 0.4,
    tags: ["graphics", "systems", "algorithms"],
    languages: ["rust", "c", "zig", "cpp"],
    concepts: ["binary table parsing", "Bézier curve flattening", "scanline rasterisation with coverage", "winding rules", "glyph atlases"],
    sourceUrl: "https://developer.apple.com/fonts/TrueType-Reference-Manual/",
  },
  {
    slug: "image-processing-pipeline",
    title: "Create an image-processing pipeline",
    summary: "Implement filters, convolutions, edge detection and histogram operations from raw pixels, then chain them.",
    description:
      "Decode an image into a pixel buffer and implement the fundamentals yourself: greyscale and colour space conversion, brightness and contrast, Gaussian blur and sharpening as convolutions, Sobel edge detection, thresholding, histogram equalisation and morphological operations. Seeing each operation as arithmetic on arrays removes a lot of mystery from computer vision.\n\nThen build the pipeline: composable stages with parameters, a preview UI or CLI, batch processing of folders, and performance work — separable kernels, integral images, SIMD or a GPU path. Add a couple of showpiece effects such as seam carving for content-aware resizing or a bilateral filter for cartooning.",
    difficulty: "INTERMEDIATE",
    estimatedHours: 8,
    popularity: 0.6,
    tags: ["graphics", "computer-vision", "algorithms"],
    languages: ["python", "rust", "cpp", "go"],
    concepts: ["pixel buffers and colour spaces", "convolution kernels", "edge detection", "histograms", "seam carving"],
  },
  {
    slug: "voxel-world-renderer",
    title: "Build a voxel world renderer",
    summary: "Render a Minecraft-style world with chunked greedy meshing, ambient occlusion and infinite terrain.",
    description:
      "Store the world as chunks of block ids, generate terrain with noise, and build a mesh per chunk that only includes visible faces. Naive one-quad-per-face rendering works for a few chunks; greedy meshing merges coplanar faces and cuts triangle counts by an order of magnitude. Add frustum culling, chunk streaming as the camera moves, and a texture atlas.\n\nThe pleasures are in the details: baked ambient occlusion in vertex colours, day-night lighting, breaking and placing blocks with raycasting, water and transparency sorting, and background mesh generation in workers or threads to keep the frame rate smooth. It combines procedural generation, real-time rendering and performance engineering in one project.",
    difficulty: "INTERMEDIATE",
    estimatedHours: 16,
    popularity: 0.55,
    tags: ["graphics", "webgl", "game-development", "procedural-generation"],
    languages: ["typescript", "rust", "cpp", "glsl"],
    concepts: ["chunked world storage", "greedy meshing", "frustum culling", "texture atlases", "voxel raycasting"],
  },
  {
    slug: "graph-visualizer-force-layout",
    title: "Build a graph visualizer with force-directed layout",
    summary: "Lay out and explore networks interactively with a physics simulation, zooming, search and clustering.",
    description:
      "Implement a force-directed layout: nodes repel each other, edges act as springs, and a simulation settles the graph into a readable arrangement. Render it on canvas or WebGL with pan, zoom, hover highlights and dragging. Feed it something real — your codebase's import graph, a social network export, package dependencies — and it becomes a genuinely useful tool.\n\nScale it: Barnes–Hut approximation for repulsion so thousands of nodes stay smooth, edge bundling or clustering with community detection, level-of-detail labels, and search that highlights paths. Export to SVG for documentation. It is a great blend of algorithms and interaction design.",
    difficulty: "INTERMEDIATE",
    estimatedHours: 8,
    popularity: 0.55,
    tags: ["visualization", "frontend", "algorithms"],
    languages: ["typescript", "javascript"],
    concepts: ["force simulation", "Barnes–Hut approximation", "canvas/WebGL rendering", "pan-zoom interaction", "community detection"],
  },
  {
    slug: "interactive-fractal-explorer",
    title: "Build an interactive fractal explorer",
    summary: "Zoom into the Mandelbrot and Julia sets in real time on the GPU with smooth colouring and deep zoom.",
    description:
      "Compute escape times per pixel in a fragment shader (or with worker threads on the CPU), map them to colours with smooth iteration counting, and add drag-to-pan and scroll-to-zoom. The first image takes minutes; the endless zoom is what keeps you exploring. Add Julia sets driven by the mouse position and a palette editor.\n\nDeep zoom exposes the limits of floating point around 1e-13, which is a great excuse to explore perturbation theory or double-double arithmetic. Add progressive rendering, bookmarks with shareable URLs and high-resolution export. It is a small, beautiful introduction to GPU programming and numerical precision.",
    difficulty: "BEGINNER",
    estimatedHours: 3,
    popularity: 0.5,
    tags: ["graphics", "creative-coding", "algorithms"],
    languages: ["typescript", "rust", "python", "glsl"],
    concepts: ["escape-time algorithms", "GPU fragment shaders", "smooth colouring", "pan-zoom coordinate mapping", "floating-point precision"],
  },
];
