import type { SeedProject } from "../types";

export const ML_PROJECTS: SeedProject[] = [
  {
    slug: "build-a-recommendation-engine",
    title: "Build a recommendation engine",
    summary: "Recommend movies from ratings with item-item collaborative filtering and matrix factorisation, and evaluate honestly.",
    description:
      "Load a public ratings dataset such as MovieLens, and start with baselines: popularity and a user's average. Then implement item-item collaborative filtering (cosine similarity between item rating vectors, weighted neighbour predictions) and matrix factorisation trained with SGD or alternating least squares. Each model is a few dozen lines, and comparing them teaches more than any tutorial.\n\nThe discipline is in evaluation: hold out each user's most recent ratings, compute precision@k, recall@k and NDCG, and resist the urge to tune on the test set. Add implicit-feedback variants, cold-start handling with content features, diversity re-ranking and explanations ('because you liked…'). You will recognise the machinery behind every 'recommended for you' shelf.",
    difficulty: "INTERMEDIATE",
    estimatedHours: 14,
    popularity: 0.75,
    tags: ["recommendation-systems", "machine-learning", "data-engineering"],
    languages: ["python", "typescript", "rust"],
    concepts: ["item-item collaborative filtering", "matrix factorisation", "top-k ranking metrics", "train/test splitting for recommenders", "cold-start strategies"],
    sourceUrl: "https://grouplens.org/datasets/movielens/",
  },
  {
    slug: "neural-network-library-with-autograd",
    title: "Build a neural-network library with automatic differentiation",
    summary: "Write a scalar autograd engine and a tiny neural network on top, then scale it to tensors.",
    description:
      "Represent each value as a node that remembers the operation and inputs that produced it. The forward pass builds a graph; the backward pass walks it in reverse topological order applying the chain rule. With that engine, a neuron is a dot product plus a nonlinearity, a layer is a list of neurons, and gradient descent is a loop. Karpathy's micrograd shows the whole thing in a hundred lines.\n\nThen make it real: tensors instead of scalars, broadcasting, matrix multiplication and its gradient, an optimiser with momentum or Adam, and a training loop that fits MNIST or a small regression. Compare your gradients to PyTorch's numerically. Understanding backpropagation this way makes every deep-learning framework feel transparent.",
    difficulty: "INTERMEDIATE",
    estimatedHours: 10,
    popularity: 0.8,
    tags: ["machine-learning", "algorithms"],
    languages: ["python", "rust", "cpp"],
    concepts: ["computational graphs", "reverse-mode automatic differentiation", "the chain rule in code", "tensor broadcasting", "optimisers"],
    sourceUrl: "https://github.com/karpathy/micrograd",
  },
  {
    slug: "mnist-classifier-from-scratch",
    title: "Train an MNIST digit classifier from scratch",
    summary: "Load the raw MNIST files, implement a small network with backpropagation by hand and reach 97% accuracy.",
    description:
      "Parse the IDX binary format, normalise the pixels, and implement a two-layer network with matrix operations only — no ML framework. Write the forward pass, cross-entropy loss, backpropagation and mini-batch gradient descent, then watch accuracy climb from 10% to over 97% in a few minutes of training. Seeing the learning curve of code you wrote yourself is a rite of passage.\n\nThen experiment: learning rate schedules, weight initialisation, dropout, and a small convolutional layer that pushes past 99%. Visualise what the first-layer weights look like and which digits your model confuses. Finish by drawing digits in a browser canvas and classifying them live.",
    difficulty: "BEGINNER",
    estimatedHours: 5,
    popularity: 0.75,
    tags: ["machine-learning"],
    languages: ["python", "rust", "typescript"],
    concepts: ["binary dataset parsing", "forward and backward passes", "cross-entropy loss", "mini-batch gradient descent", "confusion matrices"],
    sourceUrl: "http://yann.lecun.com/exdb/mnist/",
  },
  {
    slug: "tiny-language-model",
    title: "Train a tiny character-level language model",
    summary: "Build a bigram model, then an RNN, then a small transformer, and watch text generation improve at each step.",
    description:
      "Start with counting: a bigram table over characters already generates plausible-looking gibberish. Replace it with a small neural network, then an RNN, then a miniature transformer with self-attention, positional embeddings and a few blocks. Train on Shakespeare, song lyrics you wrote, or your own code, and sample from the model after every epoch to see it learn structure, then words, then style.\n\nThe point is understanding, not scale: implement attention yourself, visualise which characters attend to which, experiment with temperature and top-k sampling, and measure loss versus model size. nanoGPT is a clear reference implementation once you have built your own.",
    difficulty: "INTERMEDIATE",
    estimatedHours: 12,
    popularity: 0.7,
    tags: ["machine-learning", "nlp"],
    languages: ["python"],
    concepts: ["n-gram baselines", "recurrent networks", "self-attention", "training loops and loss curves", "sampling strategies"],
    sourceUrl: "https://github.com/karpathy/nanoGPT",
  },
  {
    slug: "naive-bayes-spam-classifier",
    title: "Build a spam classifier with naive Bayes",
    summary: "Tokenise messages, count words per class and classify with Bayes' rule — then measure precision and recall.",
    description:
      "Naive Bayes is the classic first text classifier: tokenise, count how often each word appears in spam versus ham, apply Laplace smoothing, and classify by comparing log-probabilities. Train it on a public SMS or email spam dataset and you will get surprisingly good accuracy in an hour. Inspecting the most 'spammy' and 'hammy' words is illuminating and often funny.\n\nThen do it properly: a held-out test set, precision, recall and F1, a confusion matrix, and a threshold that trades false positives for false negatives. Compare against logistic regression with TF-IDF features, and wire the model into a tiny API or a mail filter. It is a compact introduction to probabilistic classification and evaluation.",
    difficulty: "BEGINNER",
    estimatedHours: 3,
    popularity: 0.5,
    tags: ["machine-learning", "nlp"],
    languages: ["python", "go", "typescript", "java"],
    concepts: ["tokenisation", "Bayes' rule with smoothing", "log-probability arithmetic", "precision, recall and F1", "threshold tuning"],
  },
  {
    slug: "train-word-embeddings",
    title: "Train word embeddings with skip-gram",
    summary: "Implement word2vec's skip-gram with negative sampling and explore vector arithmetic on the result.",
    description:
      "Build a vocabulary from a text corpus, generate (centre word, context word) pairs with a sliding window, and train two embedding matrices so that words appearing together get similar vectors. Negative sampling makes it fast enough to run on a laptop. After training on a few million words you can compute nearest neighbours and try the famous king − man + woman ≈ queen.\n\nVisualise the embeddings with PCA or t-SNE, examine biases the corpus taught the model, and use the vectors as features in a downstream classifier to see them help. Understanding embeddings from the inside is essential background for everything modern in NLP.",
    difficulty: "INTERMEDIATE",
    estimatedHours: 8,
    popularity: 0.5,
    tags: ["nlp", "machine-learning"],
    languages: ["python", "rust"],
    concepts: ["skip-gram objective", "negative sampling", "embedding matrices", "nearest-neighbour search", "dimensionality reduction for visualisation"],
    sourceUrl: "https://arxiv.org/abs/1301.3781",
  },
  {
    slug: "q-learning-grid-world",
    title: "Teach an agent with Q-learning",
    summary: "Build a grid world, implement tabular Q-learning and watch a policy emerge — then try a neural approximator.",
    description:
      "Create a small grid with a goal, obstacles and penalties, define states, actions and rewards, and implement Q-learning: an epsilon-greedy policy, the Bellman update, and a decaying exploration rate. Render the value function as a heat map and the policy as arrows, and watch them sharpen episode by episode. It is reinforcement learning at its most transparent.\n\nThen add stochastic transitions, larger mazes, SARSA for comparison, and eventually replace the table with a small neural network (DQN-style) to solve a continuous problem such as cart-pole. Plot learning curves and study how hyperparameters change convergence. Sutton and Barto's book is free and pairs perfectly with the code.",
    difficulty: "BEGINNER",
    estimatedHours: 4,
    popularity: 0.55,
    tags: ["machine-learning", "simulation"],
    languages: ["python", "typescript", "rust"],
    concepts: ["Markov decision processes", "epsilon-greedy exploration", "the Bellman update", "value and policy visualisation", "function approximation"],
    sourceUrl: "http://incompleteideas.net/book/the-book-2nd.html",
  },
  {
    slug: "genetic-algorithm-evolution-sandbox",
    title: "Evolve solutions with genetic algorithms",
    summary: "Encode candidates as genomes, evolve them with selection, crossover and mutation, and watch fitness climb.",
    description:
      "Genetic algorithms are simple to implement and endlessly fun to watch. Build the core loop — population, fitness function, tournament selection, crossover, mutation, elitism — and apply it to a visual problem: evolving a string toward a target, a polygon painting that approximates an image, or creatures whose joints and muscles learn to walk in a small physics simulation.\n\nExperiment with population size, mutation rates and diversity preservation, and plot best and average fitness across generations. Then compare against hill climbing or simulated annealing to understand when evolution actually helps. It is a gentle introduction to optimisation with a strong creative payoff.",
    difficulty: "BEGINNER",
    estimatedHours: 4,
    popularity: 0.45,
    tags: ["machine-learning", "simulation", "creative-coding"],
    languages: ["typescript", "python", "rust"],
    concepts: ["genome encoding", "fitness functions", "selection, crossover and mutation", "diversity and premature convergence", "comparison with local search"],
  },
  {
    slug: "k-means-colour-palettes",
    title: "Extract colour palettes and compress images with k-means",
    summary: "Implement k-means clustering from scratch and use it to find dominant colours and quantise images.",
    description:
      "Treat every pixel as a point in RGB (or better, Lab) space, pick k initial centroids with k-means++, assign pixels to their nearest centroid, move centroids to the mean of their pixels and repeat until stable. The centroids are the image's dominant colours; replacing each pixel with its centroid compresses the image to k colours. Both results are visual, immediate and satisfying.\n\nExtend it with the elbow method for choosing k, mini-batch k-means for large images, dithering to hide banding, and a small web tool that generates a palette from any uploaded photo. It is a two-hour project that teaches an algorithm you will meet again and again.",
    difficulty: "BEGINNER",
    estimatedHours: 2,
    popularity: 0.5,
    tags: ["machine-learning", "graphics", "algorithms"],
    languages: ["python", "typescript", "rust"],
    concepts: ["k-means and k-means++", "colour spaces", "convergence criteria", "quantisation and dithering", "choosing k"],
  },
  {
    slug: "semantic-search-with-embeddings",
    title: "Build semantic search with local embeddings",
    summary: "Embed documents with a local model, index the vectors with your own HNSW and serve meaning-based search.",
    description:
      "Chunk a corpus (your notes, documentation, a book), compute embeddings with a small local model, and search by embedding the query and finding nearest vectors. Brute-force cosine similarity works for thousands of chunks; implementing HNSW — a hierarchical graph of neighbours — makes it fast for millions, and building it yourself teaches why approximate nearest-neighbour search is a whole field.\n\nCombine vector scores with a keyword index (BM25) for hybrid ranking, add filters and highlighting, and evaluate with a small set of query-relevance judgements. Wrap it in a CLI or a minimal web UI. It is the retrieval half of retrieval-augmented generation, and it stands on its own.",
    difficulty: "INTERMEDIATE",
    estimatedHours: 10,
    popularity: 0.6,
    tags: ["information-retrieval", "machine-learning", "nlp"],
    languages: ["python", "typescript", "rust"],
    concepts: ["text chunking and embeddings", "cosine similarity", "HNSW approximate nearest neighbours", "hybrid ranking with BM25", "retrieval evaluation"],
    sourceUrl: "https://arxiv.org/abs/1603.09320",
  },
  {
    slug: "handwriting-ocr-pipeline",
    title: "Build a handwriting OCR pipeline",
    summary: "Segment lines and characters from scanned pages, classify them with a CNN and reconstruct the text.",
    description:
      "OCR is a chain of classic vision steps followed by a model: binarise the scan, deskew it, find text lines by projection profiles or connected components, segment characters, normalise them to a fixed size and classify each with a convolutional network you train on EMNIST or your own labelled samples. Then reassemble words and lines and post-correct with a dictionary.\n\nEvery stage can be visualised and improved independently, which makes the project very debuggable. Move from character segmentation to a sequence model with CTC loss that reads whole lines, evaluate character error rate on a held-out set, and compare against an off-the-shelf engine to see where yours falls short and why.",
    difficulty: "ADVANCED",
    estimatedHours: 20,
    popularity: 0.45,
    tags: ["computer-vision", "machine-learning"],
    languages: ["python"],
    concepts: ["image binarisation and deskewing", "segmentation", "convolutional classifiers", "sequence models with CTC", "character error rate"],
  },
  {
    slug: "decision-trees-and-random-forests",
    title: "Implement decision trees and random forests",
    summary: "Grow trees with information gain, prune them, then bag them into a forest and inspect feature importance.",
    description:
      "A decision tree is a recursive search for the split that best separates the classes: for each feature and threshold, compute Gini impurity or entropy, choose the best, and recurse. Implement it for numeric and categorical features with a maximum depth and minimum leaf size, then visualise the tree — the interpretability is the appeal.\n\nBagging many trees on bootstrap samples with random feature subsets gives a random forest, one of the most reliable models in practice. Compare single-tree and forest accuracy on a few tabular datasets, compute out-of-bag error and permutation feature importance, and try gradient boosting as an ambitious follow-up. Understanding trees from the inside pays off constantly in applied ML.",
    difficulty: "INTERMEDIATE",
    estimatedHours: 6,
    popularity: 0.45,
    tags: ["machine-learning", "algorithms"],
    languages: ["python", "rust", "go", "java"],
    concepts: ["impurity measures", "recursive partitioning", "bootstrap aggregation", "out-of-bag evaluation", "feature importance"],
  },
  {
    slug: "markov-chain-text-generator",
    title: "Generate text with Markov chains",
    summary: "Build an n-gram model of any text and generate eerily plausible sentences in under two hours.",
    description:
      "Slide a window over a text, record which words follow each sequence of n words, and generate by repeatedly sampling a next word from the recorded distribution. With n = 2 you get surreal nonsense; with n = 3 or 4 on a distinctive corpus you get sentences that sound uncannily like the author. It is a tiny project with a big grin factor.\n\nThen add weighting, sentence-boundary handling, a seed for reproducibility, and generation constrained to a length or a starting phrase. Turn it into a chatbot that speaks like your group chat, a fake headline generator, or a CLI. It is also a perfect warm-up before building a real language model.",
    difficulty: "BEGINNER",
    estimatedHours: 2,
    popularity: 0.5,
    tags: ["nlp", "algorithms"],
    languages: ["python", "typescript", "go", "rust"],
    concepts: ["n-gram models", "weighted sampling", "text tokenisation", "seeded generation", "sentence boundary handling"],
  },
];
