import type { SeedProject } from "../types";

export const MOBILE_IOT_PROJECTS: SeedProject[] = [
  {
    slug: "habit-tracker-mobile-app",
    title: "Build a habit tracker with streaks and widgets",
    summary: "Create a native mobile app with local persistence, streak logic, reminders and a home-screen widget.",
    description:
      "A habit tracker is small enough to finish and rich enough to touch every part of a mobile platform: a local database for habits and check-ins, a calendar heat map, streak calculation that handles time zones and 'grace days', scheduled notifications, and a home-screen widget that shows today's progress and updates when you tap it. Build it in SwiftUI or Jetpack Compose and it doubles as a tour of modern declarative UI.\n\nAdd data export, an archive for paused habits, haptics and animation on completion, and iCloud or Google Drive backup. Then, if you want to go further, share the tracker between two devices with a small sync backend. It is the ideal first app that you will actually keep on your phone.",
    difficulty: "BEGINNER",
    estimatedHours: 8,
    popularity: 0.6,
    tags: ["mobile"],
    languages: ["kotlin", "swift"],
    concepts: ["declarative mobile UI", "local databases", "date and time zone handling", "scheduled notifications", "home-screen widgets"],
  },
  {
    slug: "barcode-pantry-inventory-app",
    title: "Build a barcode-scanning pantry inventory app",
    summary: "Scan groceries with the camera, look up products, track expiry dates and get a shopping list.",
    description:
      "Point the camera at a barcode, decode it on-device with a barcode-scanning library (or write your own EAN-13 decoder from the camera frames if you enjoy image processing), look the code up in an open food database, and add the item to your pantry with a quantity and expiry date. Notifications before food expires and a shopping list generated from what ran out make it useful the same week you build it.\n\nOn the engineering side you will handle camera permissions and frame processing, offline caching of product data, a local database with migrations, and a UI that stays responsive while decoding. Household sharing via a small backend and a barcode-generation feature for your own jars are natural extensions.",
    difficulty: "INTERMEDIATE",
    estimatedHours: 10,
    popularity: 0.45,
    tags: ["mobile", "computer-vision"],
    languages: ["kotlin", "swift"],
    concepts: ["camera frame processing", "barcode decoding", "REST API integration and caching", "local database migrations", "notifications"],
    sourceUrl: "https://developers.google.com/ml-kit/vision/barcode-scanning",
  },
  {
    slug: "step-counter-from-raw-sensors",
    title: "Build a step counter from raw accelerometer data",
    summary: "Read the accelerometer, filter and detect peaks to count steps, and validate against the OS pedometer.",
    description:
      "The phone's step counter is a signal-processing problem: read three-axis acceleration at 50–100 Hz, compute the magnitude to remove orientation, low-pass filter it, and detect peaks with adaptive thresholds and minimum spacing to count steps. Record your own walks and plot the raw and filtered signals to tune it, then compare against the platform's built-in pedometer.\n\nRun the detection in a background service that survives screen-off, store per-day counts, and build a small activity dashboard. Extend it to distinguish walking from running or cycling with a tiny classifier trained on features you extract. It is a hands-on introduction to sensors, signal processing and mobile background execution.",
    difficulty: "INTERMEDIATE",
    estimatedHours: 8,
    popularity: 0.4,
    tags: ["mobile", "algorithms", "machine-learning"],
    languages: ["kotlin", "swift"],
    concepts: ["sensor sampling", "low-pass filtering", "peak detection", "background services", "activity classification"],
    sourceUrl: "https://developer.android.com/develop/sensors-and-location/sensors/sensors_overview",
  },
  {
    slug: "ar-measuring-tape",
    title: "Build an augmented-reality measuring tape",
    summary: "Detect surfaces with ARKit or ARCore, place points in world space and measure real distances through the camera.",
    description:
      "Start an AR session, detect horizontal and vertical planes, and let the user tap to drop anchor points; the distance between anchors in world coordinates is a real-world measurement. Render the points, the connecting line and a floating label with 3D graphics that stay locked to the world as the phone moves. Getting the tap-to-hit-test-to-anchor flow right is most of the work.\n\nThen add area measurement for polygons, snapping to detected plane edges, unit switching, persistence of measurements with a screenshot, and accuracy feedback when tracking quality drops. It is a compact introduction to AR sessions, world tracking and 3D rendering on mobile.",
    difficulty: "INTERMEDIATE",
    estimatedHours: 10,
    popularity: 0.4,
    tags: ["mobile", "computer-vision", "graphics"],
    languages: ["swift", "kotlin"],
    concepts: ["AR sessions and world tracking", "plane detection and hit testing", "anchors and world coordinates", "3D overlays", "tracking-quality handling"],
    sourceUrl: "https://developer.apple.com/augmented-reality/arkit/",
  },
  {
    slug: "esp32-weather-station",
    title: "Build a Wi-Fi weather station",
    summary: "Read temperature, humidity and pressure on a microcontroller and publish them to a dashboard you host.",
    description:
      "Wire a sensor (BME280 or similar) to an ESP32, read it over I2C, connect to Wi-Fi and post readings to a small server every minute. Then build the other half: an endpoint that stores readings, a chart of the last day and week, and alerts when a value crosses a threshold. Seeing your own room's temperature curve overnight is oddly captivating.\n\nThe embedded side has real constraints to learn from: deep sleep to run on a battery for months, retrying when Wi-Fi drops, over-the-air firmware updates, and calibrating a cheap sensor. Add an outdoor unit, a small display, and export to a time-series database, and you have a personal weather network.",
    difficulty: "BEGINNER",
    estimatedHours: 6,
    popularity: 0.6,
    tags: ["iot", "embedded"],
    languages: ["c", "cpp", "python"],
    concepts: ["I2C sensor protocols", "Wi-Fi on microcontrollers", "HTTP or MQTT publishing", "deep sleep and power budgets", "over-the-air updates"],
    sourceUrl: "https://docs.espressif.com/projects/esp-idf/en/latest/esp32/",
  },
  {
    slug: "home-automation-hub",
    title: "Build a home-automation hub",
    summary: "Run a broker and rules engine that connects sensors, lights and switches with automations you write yourself.",
    description:
      "Devices publish state and accept commands over MQTT; your hub subscribes to everything, keeps a live model of the home, and runs rules such as 'if motion after sunset, turn on hallway light for five minutes'. Implement device discovery, a rules engine with time and state conditions, a dashboard showing every device, and a history of state changes.\n\nIntegrate real hardware (an ESP32 with a relay, a Zigbee dongle via a bridge) or simulate devices to start. Add scenes, scheduling with sunrise and sunset, a notification channel, and a plugin API for new device types. Home Assistant is the reference point; building your own teaches event-driven architecture in the most tangible way possible.",
    difficulty: "INTERMEDIATE",
    estimatedHours: 14,
    popularity: 0.55,
    tags: ["iot", "backend", "automation"],
    languages: ["python", "go", "typescript", "rust"],
    concepts: ["MQTT pub/sub", "device state modelling", "rules engines", "event-driven architecture", "scheduling with astronomical times"],
    sourceUrl: "https://mqtt.org/",
  },
  {
    slug: "led-matrix-handheld-game",
    title: "Build a handheld game on an LED matrix",
    summary: "Drive an LED matrix from a microcontroller with buttons and a buzzer, and write Snake or Tetris for it.",
    description:
      "Wire an 8x8 or 16x16 LED matrix, a few buttons and a piezo buzzer to a Raspberry Pi Pico or an Arduino, then write the driver: shift registers or a matrix library, multiplexing so the display refreshes without flicker, debounced input, and a game loop with a fixed timestep. Snake is the traditional first game; Tetris and Breakout follow naturally.\n\nWithout an operating system you will manage timing with hardware timers, keep the display refreshing while the game logic runs, and squeeze fonts and sprites into a few kilobytes. Add a high-score table in flash, sound effects, and a 3D-printed case. It is a wonderfully tangible way to learn embedded programming.",
    difficulty: "INTERMEDIATE",
    estimatedHours: 10,
    popularity: 0.45,
    tags: ["embedded", "game-development", "iot"],
    languages: ["c", "cpp", "rust"],
    concepts: ["display multiplexing", "hardware timers and interrupts", "input debouncing", "fixed-timestep game loops", "flash storage"],
    sourceUrl: "https://www.raspberrypi.com/documentation/pico-sdk/",
  },
  {
    slug: "custom-keyboard-firmware",
    title: "Build a mechanical keyboard and write its firmware",
    summary: "Hand-wire a key matrix, then write firmware that scans it, debounces, handles layers and speaks USB HID.",
    description:
      "A keyboard is a grid of switches: rows are driven one at a time and columns are read, which lets a handful of pins scan dozens of keys. Wire a small matrix (a macropad is a great start), then write firmware that scans it, debounces each key, maps positions to keycodes through layers, and reports over USB as a HID device so any computer accepts it without drivers.\n\nOnce the basics work, add tap-hold keys, macros, rotary encoders, RGB, and a configuration file so the layout is data. Study QMK's architecture and compare it to yours. There is something deeply satisfying about typing on hardware and firmware you built.",
    difficulty: "INTERMEDIATE",
    estimatedHours: 12,
    popularity: 0.5,
    tags: ["embedded", "iot"],
    languages: ["c", "rust"],
    concepts: ["key matrix scanning", "debouncing", "USB HID descriptors", "layers and tap-hold logic", "firmware configuration"],
    sourceUrl: "https://docs.qmk.fm/",
  },
  {
    slug: "quadcopter-flight-controller",
    title: "Write a quadcopter flight controller",
    summary: "Fuse IMU data, run PID loops at high rate and stabilise a small drone — first in a simulator, then for real.",
    description:
      "A flight controller reads a gyroscope and accelerometer hundreds of times a second, estimates orientation with a complementary or Kalman filter, and runs PID controllers on roll, pitch and yaw that mix into four motor commands. Build it first in a physics simulation you write yourself so you can tune gains without breaking propellers, then flash it to a microcontroller on a small frame.\n\nThe engineering is demanding and rewarding: sensor calibration, filter tuning, control-loop timing under interrupts, failsafes when the radio link drops, and logging flight data for analysis. Add altitude hold with a barometer and position hold with GPS as long-term goals. Betaflight's source and documentation are an excellent reference once you have your own loop flying.",
    difficulty: "ADVANCED",
    estimatedHours: 40,
    popularity: 0.4,
    tags: ["embedded", "iot", "simulation", "algorithms"],
    languages: ["c", "cpp", "rust"],
    concepts: ["IMU sensor fusion", "PID control", "real-time control loops", "motor mixing", "failsafes and telemetry"],
    sourceUrl: "https://betaflight.com/",
  },
  {
    slug: "e-ink-dashboard",
    title: "Build an e-ink dashboard",
    summary: "Render calendar, weather and to-dos to an always-on e-paper display that sips power and looks like paper.",
    description:
      "E-paper holds an image with no power, so a small board can wake every fifteen minutes, fetch data, redraw and sleep. Render a dashboard image server-side (calendar events, weather, tasks, a quote) with a layout you design in code, send it to a microcontroller or a Raspberry Pi driving the display, and handle the partial-refresh quirks that make e-ink both charming and fiddly.\n\nDesign for the medium: high-contrast typography, dithering for images, and a layout that stays legible from across a room. Add a battery and measure how many months it lasts, a button to cycle views, and a physical frame. It is a calm little product that combines embedded work, rendering and API integration.",
    difficulty: "BEGINNER",
    estimatedHours: 5,
    popularity: 0.45,
    tags: ["iot", "embedded", "automation"],
    languages: ["python", "c"],
    concepts: ["e-paper display drivers", "server-side image rendering", "deep sleep scheduling", "dithering", "battery budgeting"],
    sourceUrl: "https://www.waveshare.com/wiki/Main_Page",
  },
];
