import type { SeedProject } from "../types";

export const NETWORKING_PROJECTS: SeedProject[] = [
  {
    slug: "implement-a-dns-resolver",
    title: "Implement a DNS resolver",
    summary: "Build a resolver that constructs DNS packets by hand and walks from the root servers to an answer.",
    description:
      "DNS messages are compact binary structures: a 12-byte header, a question section and resource records with a clever pointer-based name compression scheme. Write an encoder and decoder for them, send a query over UDP to a public resolver, and print the A record for a domain. That alone demystifies a protocol you use thousands of times a day.\n\nThen make it a real recursive resolver: start from the root server hints, follow NS referrals through the TLD servers to the authoritative servers, handle CNAME chains and glue records, and cache answers respecting TTLs. Add support for AAAA, MX and TXT, retry over TCP when responses are truncated, and finally serve queries yourself on port 53 so your machine can use it. Comparing your traces to dig +trace is a nice check.",
    difficulty: "INTERMEDIATE",
    estimatedHours: 8,
    popularity: 0.75,
    tags: ["networking", "systems"],
    languages: ["rust", "go", "python", "c"],
    concepts: ["binary protocol encoding", "DNS name compression", "recursive resolution", "UDP and TCP fallback", "TTL-based caching"],
    sourceUrl: "https://www.rfc-editor.org/rfc/rfc1035",
  },
  {
    slug: "websocket-server-from-scratch",
    title: "Build a WebSocket server from the RFC",
    summary: "Implement the HTTP upgrade handshake and WebSocket framing yourself, then power a live demo with it.",
    description:
      "A WebSocket connection begins as an HTTP request with an Upgrade header and a random key; the server answers with a SHA-1-derived accept value and from then on the socket carries framed binary messages. Implement the handshake, then the frame format: opcodes, the mask bit, payload lengths that switch between 7, 16 and 64 bits, fragmentation, and control frames for ping, pong and close.\n\nOnce a browser can send you messages and receive replies, build something on top: a chat room, a live cursor demo or a collaborative counter. Then handle the messy parts — malformed frames, oversized payloads, slow clients and back-pressure — and run the Autobahn test suite against your server to see how conformant it really is.",
    difficulty: "INTERMEDIATE",
    estimatedHours: 8,
    popularity: 0.65,
    tags: ["networking", "backend", "web"],
    languages: ["typescript", "go", "rust", "python"],
    concepts: ["HTTP upgrade handshake", "binary framing and masking", "control frames", "back-pressure", "protocol conformance testing"],
    sourceUrl: "https://www.rfc-editor.org/rfc/rfc6455",
  },
  {
    slug: "reverse-proxy-and-load-balancer",
    title: "Build a reverse proxy and load balancer",
    summary: "Route incoming HTTP traffic across several backends with health checks, retries and hot config reloads.",
    description:
      "Accept HTTP connections, pick a backend, forward the request and stream the response back while rewriting hop-by-hop headers and adding X-Forwarded-For. Implement round-robin, least-connections and consistent-hash balancing and watch how each behaves when one backend slows down. Active health checks and passive failure detection take unhealthy backends out of rotation automatically.\n\nThen add the features that make proxies like nginx, HAProxy and Envoy valuable: connection pooling to backends, per-route timeouts and retries with budgets, request and response buffering limits, TLS termination, access logs, and reloading configuration without dropping connections. Load-test it with a mix of fast and slow backends and see whether your retry logic makes an outage better or worse.",
    difficulty: "INTERMEDIATE",
    estimatedHours: 12,
    popularity: 0.65,
    tags: ["networking", "backend", "distributed-systems"],
    languages: ["go", "rust", "typescript"],
    concepts: ["HTTP proxying semantics", "load-balancing algorithms", "health checking", "timeouts and retry budgets", "graceful reloads"],
  },
  {
    slug: "write-a-bittorrent-client",
    title: "Write a BitTorrent client",
    summary: "Parse a .torrent file, talk to the tracker and peers, and download a real file piece by piece.",
    description:
      "Decode the bencoded metainfo file, compute the info hash, announce yourself to the tracker over HTTP and receive a list of peers. Then implement the peer wire protocol: the handshake, bitfields, interested and choke messages, and requesting 16 KiB blocks that you assemble into pieces and verify against SHA-1 hashes before writing to disk. Downloading a Linux ISO with your own client is a genuinely thrilling milestone.\n\nWith the basics working, tackle piece selection (rarest-first), managing dozens of concurrent peers, endgame mode, seeding back to others, and resuming an interrupted download. Adding DHT support means implementing a Kademlia routing table, which is a distributed-systems project in itself.",
    difficulty: "ADVANCED",
    estimatedHours: 30,
    popularity: 0.7,
    tags: ["networking", "p2p", "systems"],
    languages: ["go", "rust", "python"],
    concepts: ["bencoding", "peer wire protocol", "piece verification with hashes", "concurrent peer management", "rarest-first scheduling"],
    sourceUrl: "https://www.bittorrent.org/beps/bep_0003.html",
  },
  {
    slug: "tcp-chat-server",
    title: "Build a TCP chat server and client",
    summary: "Write a multi-user chat over raw TCP with rooms, nicknames and a simple line-based protocol.",
    description:
      "Accept many clients at once, read lines from each, and broadcast them to everyone else in the room. It is a classic first networking project because every design decision is visible: how do you handle many connections (threads, select, async), how do you frame messages, what happens when a client disconnects mid-line, and how do you avoid one slow client blocking everyone else.\n\nDesign a tiny text protocol with commands such as /nick, /join and /msg, write a terminal client with a proper input line that does not get clobbered by incoming messages, and add message history on join. Later you can secure it with TLS or replace the raw protocol with WebSockets and a browser client.",
    difficulty: "BEGINNER",
    estimatedHours: 4,
    popularity: 0.65,
    tags: ["networking", "backend", "cli"],
    languages: ["python", "go", "rust", "c"],
    concepts: ["TCP sockets", "message framing", "handling many connections", "broadcast and rooms", "terminal input handling"],
    sourceUrl: "https://beej.us/guide/bgnet/",
  },
  {
    slug: "packet-sniffer-and-decoder",
    title: "Write a packet sniffer and protocol decoder",
    summary: "Capture packets from your network interface and decode Ethernet, IP, TCP, UDP and DNS by hand.",
    description:
      "Open a raw socket or use libpcap to capture frames from a network interface on your own machine, then peel off the layers: Ethernet header, IPv4/IPv6 header with its options and fragmentation fields, TCP with flags, sequence numbers and window sizes, UDP, and finally application protocols such as DNS and HTTP. Print each packet in a readable one-line summary like tcpdump does.\n\nAdd a BPF-style filter expression, TCP stream reassembly so you can follow a conversation, statistics per host and per protocol, and writing to pcap files that Wireshark can open. Capturing your own traffic while you browse is a memorable way to see what leaves your machine in plaintext.",
    difficulty: "INTERMEDIATE",
    estimatedHours: 10,
    popularity: 0.5,
    tags: ["networking", "security", "systems"],
    languages: ["c", "rust", "python", "go"],
    concepts: ["raw sockets and libpcap", "protocol header parsing", "TCP stream reassembly", "pcap file format", "filter expressions"],
    sourceUrl: "https://www.tcpdump.org/",
  },
  {
    slug: "build-a-rate-limiter",
    title: "Build a rate limiter",
    summary: "Implement token bucket, sliding window and leaky bucket limiters and expose them as HTTP middleware.",
    description:
      "Rate limiting looks trivial and hides real design choices. Implement a token bucket that refills at a fixed rate, a sliding-window log that keeps exact timestamps, and a sliding-window counter that approximates it with far less memory. Wrap them in middleware that returns 429 with Retry-After and rate-limit headers, keyed by client IP or API key.\n\nThen make it robust: expire idle keys so memory stays bounded, make the limiter safe under concurrent requests, and think about what happens with several server instances — a shared store, or accepting slightly inaccurate limits per node. Write a simulation that fires bursty traffic at each algorithm and plots accepted requests over time to see their different characters.",
    difficulty: "BEGINNER",
    estimatedHours: 4,
    popularity: 0.55,
    tags: ["backend", "networking", "distributed-systems"],
    languages: ["go", "typescript", "rust", "java"],
    concepts: ["token bucket", "sliding windows", "HTTP middleware", "concurrency safety", "memory-bounded caches"],
  },
  {
    slug: "userspace-tcp-ip-stack",
    title: "Implement a userspace TCP/IP stack",
    summary: "Read raw IP packets from a TUN device and implement TCP's handshake, retransmission and flow control yourself.",
    description:
      "Create a TUN interface, and every packet the kernel routes to it lands in your program as raw bytes. Parse the IPv4 header, respond to ICMP pings, then implement TCP: the three-way handshake, sequence and acknowledgement numbers, the receive window, retransmission timers, and connection teardown. When curl fetches a page through a TCP stack you wrote, you will understand networking at a level few developers reach.\n\nGo further with congestion control (slow start, congestion avoidance), Nagle's algorithm and delayed ACKs, out-of-order segment buffering, and a socket-like API so an HTTP server can run on top. Wireshark becomes your debugger and the RFCs your documentation.",
    difficulty: "ADVANCED",
    estimatedHours: 50,
    popularity: 0.5,
    tags: ["networking", "systems"],
    languages: ["rust", "c", "go"],
    concepts: ["TUN/TAP devices", "IPv4 and ICMP", "TCP state machine", "retransmission and flow control", "congestion control"],
    sourceUrl: "https://www.kernel.org/doc/Documentation/networking/tuntap.txt",
  },
  {
    slug: "mdns-service-discovery",
    title: "Build local service discovery with mDNS",
    summary: "Announce and discover services on your LAN with multicast DNS, the protocol behind Bonjour and AirPrint.",
    description:
      "Multicast DNS reuses the DNS packet format over UDP multicast so devices can find each other with no central server. Implement a responder that announces a service (its name, port and TXT metadata) and a browser that queries for a service type and collects answers, handling the probing and conflict-resolution rules that keep names unique.\n\nBuild something with it: a command-line tool that lists every printer, speaker and dev server on your network, or two of your own apps that find each other automatically. Handle interfaces coming and going, cache-flush records and goodbye packets on shutdown. This is a small, practical protocol that touches multicast, DNS encoding and the realities of home networks.",
    difficulty: "INTERMEDIATE",
    estimatedHours: 8,
    popularity: 0.35,
    tags: ["networking", "iot"],
    languages: ["go", "rust", "python", "swift"],
    concepts: ["UDP multicast", "DNS record types", "probing and conflict resolution", "service browsing", "network interface events"],
    sourceUrl: "https://www.rfc-editor.org/rfc/rfc6762",
  },
  {
    slug: "ntp-client-and-clock-drift",
    title: "Write an NTP client and measure your clock drift",
    summary: "Query time servers with hand-built NTP packets, compute offset and delay, and log how your clock wanders.",
    description:
      "An NTP packet is 48 bytes and the arithmetic to turn four timestamps into a clock offset and round-trip delay fits on an index card. Build the packet, send it to a public time server over UDP, parse the reply and print how far off your machine's clock is. Query several servers and combine the results, discarding outliers.\n\nRun it every minute for a day and plot your clock's drift; then think about how you would discipline the clock gradually rather than jumping it. This is a short project with a long tail: it introduces the timing assumptions that distributed systems, TLS certificate validation and log correlation all silently rely on.",
    difficulty: "BEGINNER",
    estimatedHours: 3,
    popularity: 0.35,
    tags: ["networking", "systems", "distributed-systems"],
    languages: ["python", "go", "rust", "c"],
    concepts: ["UDP messaging", "binary timestamp formats", "offset and delay estimation", "outlier rejection", "clock discipline"],
    sourceUrl: "https://www.rfc-editor.org/rfc/rfc5905",
  },
  {
    slug: "tls-1-3-client-handshake",
    title: "Implement a TLS 1.3 client handshake",
    summary: "Speak TLS to a real server using only a crypto library's primitives: key exchange, key schedule, record encryption.",
    description:
      "Send a ClientHello with an X25519 key share, receive the ServerHello, derive the handshake secrets with HKDF according to the TLS 1.3 key schedule, decrypt the server's certificate and Finished messages, verify the transcript hash, and send your own Finished. Then encrypt an HTTP GET inside application-data records and decrypt the response. Every byte is specified in RFC 8446, and Wireshark can decrypt your session if you log the keys.\n\nYou may skip certificate chain validation at first (and must not for real use), then add it: parse X.509, verify signatures up to a trusted root, check names and expiry. This project turns TLS from a black box into a sequence of understandable steps and gives you healthy respect for the details that make it secure.",
    difficulty: "ADVANCED",
    estimatedHours: 40,
    popularity: 0.4,
    tags: ["networking", "cryptography", "security"],
    languages: ["rust", "go", "python"],
    concepts: ["TLS record and handshake layers", "X25519 key exchange", "HKDF key schedule", "AEAD record encryption", "X.509 certificate validation"],
    sourceUrl: "https://www.rfc-editor.org/rfc/rfc8446",
  },
  {
    slug: "protobuf-wire-format-codec",
    title: "Write a Protocol Buffers encoder and decoder",
    summary: "Implement the protobuf wire format and generate typed code from .proto files.",
    description:
      "The protobuf wire format is small: field numbers combined with wire types, varints for integers, length-delimited bytes for strings and nested messages, and zigzag encoding for signed numbers. Write an encoder and decoder that round-trips messages against the official implementation, including unknown fields, repeated and packed fields, and default values.\n\nThen parse .proto files and generate typed classes or structs in your language, with a small runtime for serialisation. Benchmark against JSON to see why binary formats exist, and compare your design decisions to those of MessagePack and CBOR. It is a compact project that touches parsing, code generation and binary formats at once.",
    difficulty: "INTERMEDIATE",
    estimatedHours: 8,
    popularity: 0.4,
    tags: ["backend", "networking", "compilers"],
    languages: ["typescript", "go", "rust", "python"],
    concepts: ["varint and zigzag encoding", "tag/wire-type framing", "schema parsing", "code generation", "serialisation benchmarks"],
    sourceUrl: "https://protobuf.dev/programming-guides/encoding/",
  },
];
