import type { SeedProject } from "../types";

export const SECURITY_PROJECTS: SeedProject[] = [
  {
    slug: "create-a-password-manager",
    title: "Create a password manager",
    summary: "Build a vault encrypted with a key derived from a master password, with a CLI, generator and safe clipboard handling.",
    description:
      "The core is a file format: a header with a random salt and KDF parameters, and a body encrypted with an authenticated cipher (AES-GCM or XChaCha20-Poly1305) under a key derived from the master password with Argon2id. Implement add, get, list, generate and remove commands, and think carefully about the details that matter: constant-time comparisons, zeroing secrets in memory where your language allows, and clearing the clipboard after a timeout.\n\nThen add what makes it usable — search, TOTP codes, an import from CSV, a browser extension or a small GUI — and what makes it trustworthy: a threat model written down, tests for the file format, and a design for syncing the encrypted vault across devices without the server ever seeing plaintext. Reading how KeePass and Bitwarden approach the same problems is instructive.",
    difficulty: "INTERMEDIATE",
    estimatedHours: 14,
    popularity: 0.75,
    tags: ["security", "cryptography", "cli"],
    languages: ["rust", "go", "typescript", "swift"],
    concepts: ["key derivation (Argon2id)", "authenticated encryption", "vault file formats", "secure memory and clipboard handling", "threat modelling"],
    sourceUrl: "https://github.com/P-H-C/phc-winner-argon2",
  },
  {
    slug: "build-a-totp-authenticator",
    title: "Build a TOTP authenticator",
    summary: "Generate the same six-digit codes as Google Authenticator from a shared secret, a clock and HMAC.",
    description:
      "Time-based one-time passwords are simple once you see them: HMAC the current 30-second time step with a shared secret, dynamically truncate the result to 31 bits and take it modulo a million. Implement HOTP and TOTP per the RFCs, verify against the published test vectors, decode secrets from otpauth:// URIs and QR codes, and show a countdown until the next code.\n\nBuild it as a CLI, a mobile app or a browser extension, then add the operational features: encrypted storage of secrets, backup and restore, clock-drift tolerance windows, and generating your own provisioning QR codes for a service you run. It is a short, concrete project that demystifies two-factor authentication.",
    difficulty: "BEGINNER",
    estimatedHours: 3,
    popularity: 0.6,
    tags: ["security", "cryptography", "mobile"],
    languages: ["typescript", "kotlin", "swift", "python", "go"],
    concepts: ["HMAC-based one-time passwords", "time-step counters", "base32 and otpauth URIs", "test vectors", "encrypted secret storage"],
    sourceUrl: "https://www.rfc-editor.org/rfc/rfc6238",
  },
  {
    slug: "end-to-end-encrypted-chat",
    title: "Build an end-to-end encrypted chat",
    summary: "Implement X3DH key agreement and the Double Ratchet so a relay server can never read messages.",
    description:
      "Design a chat where the server only stores ciphertext. Clients publish identity, signed-prekey and one-time-prekey bundles; a sender performs the X3DH handshake to establish a shared secret with someone who is offline; and the Double Ratchet derives a fresh key for every message, giving forward secrecy and post-compromise security. Use a vetted crypto library for the primitives and implement the protocol logic yourself.\n\nBuild the relay server, two clients, out-of-order message handling with skipped-key storage, and safety-number verification. Write down the threat model and what the design does not protect (metadata, compromised endpoints). It is a deep and rewarding tour of modern messaging security, following the published Signal specifications closely.",
    difficulty: "ADVANCED",
    estimatedHours: 30,
    popularity: 0.55,
    tags: ["cryptography", "security", "networking"],
    languages: ["typescript", "rust", "go"],
    concepts: ["X3DH key agreement", "Double Ratchet", "forward secrecy", "prekey bundles", "threat modelling"],
    sourceUrl: "https://signal.org/docs/specifications/doubleratchet/",
  },
  {
    slug: "encrypted-file-vault",
    title: "Build an encrypted file vault",
    summary: "Encrypt files and folders with a modern AEAD, streaming so large files never fit in memory, in an age-like format.",
    description:
      "Design a small file format: a header identifying the version, a random file key wrapped for each recipient (a passphrase via scrypt or Argon2, or an X25519 public key), and the payload encrypted in fixed-size chunks with ChaCha20-Poly1305 so a multi-gigabyte file streams through with constant memory and truncation is detected. Then write encrypt, decrypt and inspect commands.\n\nThe details are what make it worthwhile: chunk counters that prevent reordering, an authenticated header, clear error messages that never leak partial plaintext, and test vectors so the format can be reimplemented. Add directory support with a tar-like archive stage, and compare your design decisions to age's published spec.",
    difficulty: "INTERMEDIATE",
    estimatedHours: 8,
    popularity: 0.55,
    tags: ["cryptography", "security", "cli"],
    languages: ["rust", "go", "python"],
    concepts: ["AEAD ciphers", "streaming chunked encryption", "key wrapping for multiple recipients", "file format design", "test vectors"],
    sourceUrl: "https://age-encryption.org/",
  },
  {
    slug: "secrets-scanner-for-repositories",
    title: "Build a secrets scanner for git repositories",
    summary: "Find leaked API keys and credentials across a repo's whole history with regexes, entropy and verification.",
    description:
      "Walk every commit and blob in a repository (not just the working tree — deleted secrets live on in history), and scan for credentials with a library of provider-specific patterns (cloud keys, tokens, private key headers) plus a Shannon-entropy heuristic for generic high-entropy strings. Report file, commit and line, and suppress known false positives with an allowlist.\n\nThen make it something a team would run: a pre-commit hook mode that scans staged changes in milliseconds, a CI mode with machine-readable output, optional verification that checks whether a found key is still live against the provider's API, and clear remediation guidance. Tools like TruffleHog and gitleaks show the design space; building your own teaches how they trade recall against noise.",
    difficulty: "INTERMEDIATE",
    estimatedHours: 8,
    popularity: 0.45,
    tags: ["security", "devtools", "cli"],
    languages: ["go", "rust", "python"],
    concepts: ["git object traversal", "pattern libraries and regex performance", "entropy heuristics", "pre-commit hooks", "false-positive management"],
    sourceUrl: "https://github.com/trufflesecurity/trufflehog",
  },
  {
    slug: "tamper-evident-audit-log",
    title: "Build a tamper-evident audit log",
    summary: "Chain log entries with hashes, publish Merkle roots and let anyone prove an entry is included and nothing was altered.",
    description:
      "Every audit entry includes the hash of the previous one, so changing history changes every later hash. Build a Merkle tree over the entries so a client can verify that a specific entry is included with a logarithmic-size proof, and periodically sign and publish the root. That is the core idea behind Certificate Transparency and many compliance systems.\n\nImplement inclusion proofs, consistency proofs between two tree sizes (proving the log is append-only), a verifier CLI, and a monitor that watches for roots that do not extend earlier ones. Add a small HTTP API and a UI that visualises the tree. It is a compact, practical introduction to verifiable data structures.",
    difficulty: "INTERMEDIATE",
    estimatedHours: 8,
    popularity: 0.4,
    tags: ["security", "cryptography", "backend", "distributed-systems"],
    languages: ["go", "typescript", "rust"],
    concepts: ["hash chains", "Merkle trees", "inclusion and consistency proofs", "signed tree heads", "verifiers and monitors"],
    sourceUrl: "https://certificate.transparency.dev/",
  },
  {
    slug: "sandbox-for-untrusted-code",
    title: "Build a sandbox for running untrusted code",
    summary: "Execute submitted programs safely with namespaces, seccomp filters, resource limits and a clean API.",
    description:
      "Online judges and code-runner services need to execute strangers' code without letting it read files, open sockets or fork-bomb the machine. Build a runner that launches the program in fresh namespaces with a minimal root filesystem, applies a seccomp-BPF allowlist of system calls, sets rlimits and cgroup limits for CPU, memory and processes, and enforces a wall-clock timeout, capturing stdout, stderr and exit status.\n\nThen harden it: drop capabilities, no-new-privileges, a read-only filesystem with a tmpfs scratch area, and a network namespace with no interfaces. Write tests that try to escape — read /etc/shadow, connect outward, spawn a thousand processes — and confirm they fail. Comparing your design with gVisor and Firecracker will show you the next layers of defence.",
    difficulty: "ADVANCED",
    estimatedHours: 20,
    popularity: 0.45,
    tags: ["security", "systems", "operating-systems"],
    languages: ["rust", "go", "c"],
    concepts: ["seccomp-BPF filters", "namespaces and minimal rootfs", "rlimits and cgroups", "capability dropping", "escape testing"],
    sourceUrl: "https://man7.org/linux/man-pages/man2/seccomp.2.html",
  },
  {
    slug: "web-security-lab",
    title: "Build a deliberately vulnerable web app, then fix it",
    summary: "Write an app with classic vulnerabilities on purpose, exploit each one locally, then patch it properly with tests.",
    description:
      "The fastest way to understand web security is to build the bugs yourself. Create a small app with a login, comments and file uploads that contains SQL injection, stored and reflected XSS, CSRF, insecure direct object references, broken access control and a path traversal — one per feature. For each, write a local proof of concept that demonstrates the impact on your own instance.\n\nThen fix each properly: parameterised queries, output encoding and a Content Security Policy, CSRF tokens and SameSite cookies, authorisation checks in one place, and safe file handling. Write regression tests that would fail if the vulnerability came back, and add security headers and rate limiting. You will read the OWASP Top Ten afterwards as a list of things you have personally broken and repaired.",
    difficulty: "INTERMEDIATE",
    estimatedHours: 10,
    popularity: 0.5,
    tags: ["security", "web", "backend"],
    languages: ["typescript", "python", "java"],
    concepts: ["injection and output encoding", "CSRF defences", "access control design", "Content Security Policy", "security regression tests"],
    sourceUrl: "https://owasp.org/www-project-top-ten/",
  },
];
