import type { SeedProject } from "../types";

export const SYSTEMS_PROJECTS: SeedProject[] = [
  {
    slug: "build-your-own-redis",
    title: "Build your own Redis",
    summary: "Implement an in-memory key-value server that speaks the real Redis protocol so redis-cli can talk to it.",
    description:
      "Start with a TCP listener that parses RESP (the Redis Serialization Protocol) and answers PING, GET, SET and DEL. Because RESP is tiny and well documented, a working server that real clients can talk to fits in an afternoon; the rest of the project is about doing it well: an event loop that multiplexes thousands of connections without a thread per client, key expiry with lazy and active eviction, and pipelining so clients can send many commands before reading replies.\n\nFrom there the project branches wherever your curiosity goes. Add lists, hashes and sorted sets and you are implementing skip lists and hash tables by hand. Add RDB snapshots or an append-only file and you are reasoning about durability and fsync. Add replication and you are building a log-shipping protocol. Each layer is small enough to finish and large enough to teach something a framework normally hides.",
    difficulty: "INTERMEDIATE",
    estimatedHours: 20,
    popularity: 0.92,
    tags: ["systems", "networking", "databases", "backend"],
    languages: ["rust", "go", "c"],
    concepts: ["RESP protocol parsing", "event loops and non-blocking I/O", "hash tables and expiry", "persistence and fsync", "replication basics"],
    sourceUrl: "https://build-your-own.org/redis/",
  },
  {
    slug: "write-an-http-server",
    title: "Write an HTTP/1.1 server from raw sockets",
    summary: "Serve static files and simple routes over HTTP/1.1 using nothing but a socket API and the RFC.",
    description:
      "Open a listening socket, accept a connection, read bytes until you find the blank line that ends the request head, parse the request line and headers, and write back a valid response. That loop is the whole of HTTP/1.1 at its core, and getting a browser to render a page you served by hand is a satisfying moment. Then the details arrive: Content-Length versus chunked transfer encoding, keep-alive connections, percent-decoding paths safely so ../ cannot escape the document root, and HEAD requests.\n\nOnce the basics work, add concurrency (a thread pool or an async runtime), a tiny router with path parameters, gzip responses, range requests for video seeking and a graceful shutdown that drains in-flight requests. Compare your throughput against nginx with a load-testing tool and figure out where the time goes.",
    difficulty: "INTERMEDIATE",
    estimatedHours: 12,
    popularity: 0.9,
    tags: ["networking", "systems", "backend"],
    languages: ["c", "rust", "go", "python"],
    concepts: ["TCP sockets", "HTTP/1.1 message framing", "keep-alive and chunked encoding", "path traversal defences", "concurrency models"],
    sourceUrl: "https://www.rfc-editor.org/rfc/rfc9112",
  },
  {
    slug: "build-a-unix-shell",
    title: "Build a Unix shell",
    summary: "Write a shell that runs commands, pipes them together, redirects files and handles job control.",
    description:
      "A shell is a small program with a surprising number of operating-system concepts inside it. Read a line, tokenise it, fork a child, exec the program, wait for it and print a prompt again. Then implement pipes by wiring one child's stdout to the next child's stdin, redirections with dup2, environment variables, and built-ins such as cd and export that must run in the parent process.\n\nJob control is where it gets interesting: background jobs with &, Ctrl-Z to suspend, fg and bg to resume, and correct handling of process groups and terminal signals so that Ctrl-C kills the foreground job and not your shell. Finish with tab completion, history and a small scripting layer (if/for/while) if you want to keep going.",
    difficulty: "INTERMEDIATE",
    estimatedHours: 15,
    popularity: 0.85,
    tags: ["systems", "operating-systems", "cli", "terminal"],
    languages: ["c", "rust", "go"],
    concepts: ["fork/exec/wait", "pipes and file descriptors", "signals and process groups", "tokenising and parsing", "terminal control"],
  },
  {
    slug: "write-a-memory-allocator",
    title: "Write a memory allocator",
    summary: "Implement malloc, free and realloc on top of raw pages and learn why allocators are hard.",
    description:
      "Request memory from the operating system with sbrk or mmap, carve it into blocks with headers, and hand pointers back to callers. The first version — a bump allocator that never frees — takes fifteen minutes. A free list with coalescing of neighbouring blocks takes an evening. Segregated size classes, alignment guarantees and thread-local caches take you into the design space that jemalloc and mimalloc live in.\n\nMeasure fragmentation and throughput against the system allocator with a benchmark that mimics a real workload, and preload your allocator into an existing program with LD_PRELOAD to see whether it survives. Add poisoning of freed memory and canaries to catch use-after-free bugs, and you have also built a tiny memory debugger.",
    difficulty: "INTERMEDIATE",
    estimatedHours: 8,
    popularity: 0.7,
    tags: ["systems", "operating-systems", "data-structures"],
    languages: ["c", "zig", "rust"],
    concepts: ["sbrk and mmap", "free lists and coalescing", "alignment", "fragmentation trade-offs", "LD_PRELOAD interposition"],
    sourceUrl: "https://danluu.com/malloc-tutorial/",
  },
  {
    slug: "toy-container-runtime",
    title: "Build a toy container runtime",
    summary: "Isolate a process with Linux namespaces, cgroups and a chroot to see what Docker actually does.",
    description:
      "Containers are ordinary processes with a few kernel features applied. Clone a child with new PID, mount, UTS and network namespaces, pivot into a root filesystem you extracted from an image, set a hostname, mount /proc, and exec the requested command. Suddenly ps shows a single process and the machine looks empty from inside.\n\nNext, limit the process with cgroups (CPU shares, memory caps, PID limits), drop capabilities, add a seccomp filter, and give the container a virtual ethernet pair with NAT so it can reach the internet. Reading an OCI image layout so your runtime can pull real images from a registry is a strong finish. Along the way you will build an accurate mental model of the isolation guarantees containers do and do not provide.",
    difficulty: "ADVANCED",
    estimatedHours: 20,
    popularity: 0.65,
    tags: ["systems", "operating-systems", "security"],
    languages: ["go", "rust", "c"],
    concepts: ["Linux namespaces", "cgroups v2", "pivot_root and mounts", "capabilities and seccomp", "OCI image layout"],
    sourceUrl: "https://man7.org/linux/man-pages/man7/namespaces.7.html",
  },
  {
    slug: "thread-pool-with-work-stealing",
    title: "Build a thread pool with work stealing",
    summary: "Write a task scheduler where idle workers steal work from busy ones and measure the difference.",
    description:
      "Begin with a fixed pool of worker threads pulling closures from a single mutex-protected queue. It works, but under load every worker contends on one lock. Give each worker its own double-ended queue: it pushes and pops from one end, and idle workers steal from the other end of a random victim. This is the design behind Java's ForkJoinPool, Rust's rayon and Go's scheduler.\n\nInstrument it. Count steals, measure tail latency, and compare against the naive queue on a recursive workload such as parallel quicksort or a Fibonacci tree. Then add futures so callers can await results, graceful shutdown, and panic/exception isolation so one bad task cannot take down a worker. Writing the deque correctly with atomics rather than a lock is an optional deep end.",
    difficulty: "INTERMEDIATE",
    estimatedHours: 10,
    popularity: 0.5,
    tags: ["concurrency", "systems"],
    languages: ["rust", "cpp", "java", "go"],
    concepts: ["work-stealing deques", "mutexes and condition variables", "atomics and memory ordering", "futures/promises", "benchmarking parallel code"],
  },
  {
    slug: "event-loop-from-scratch",
    title: "Build an event loop with epoll or kqueue",
    summary: "Write a single-threaded async I/O core — the thing under Node.js and Tokio — from the syscalls up.",
    description:
      "Register non-blocking sockets and timers with epoll (Linux) or kqueue (macOS/BSD), block waiting for readiness, and dispatch callbacks. With that loop you can serve tens of thousands of idle connections from one thread. Add a timer heap for setTimeout-style scheduling, a run-later queue, and correct handling of partial reads and writes with per-connection buffers.\n\nOnce the loop works, put an echo server, then a chat server, then a small HTTP server on top and load-test them. If your language has coroutines or async/await, build the glue that turns readiness events into resumed tasks and you have written a miniature runtime. Reading how libuv and mio structure the same problem after you have built your own is a great way to close the loop.",
    difficulty: "ADVANCED",
    estimatedHours: 16,
    popularity: 0.55,
    tags: ["systems", "concurrency", "networking"],
    languages: ["c", "rust", "zig"],
    concepts: ["epoll/kqueue readiness APIs", "non-blocking sockets", "timer heaps", "buffer management", "async runtimes"],
  },
  {
    slug: "userspace-filesystem-with-fuse",
    title: "Write a userspace filesystem with FUSE",
    summary: "Mount a filesystem you wrote — backed by memory, a zip file or an HTTP API — and use it with normal tools.",
    description:
      "FUSE lets an ordinary program answer filesystem calls: lookup, getattr, readdir, open, read, write. Implement those callbacks over an in-memory tree and you can cd into your filesystem, ls it and edit files with your editor. Then back it with something interesting: a zip or tar archive exposed as directories, a key-value store, or a remote API where each endpoint appears as a file.\n\nThe hard parts are the ones real filesystems face: inode numbers that stay stable, permissions, partial and unaligned reads, concurrent access, and caching so that stat storms from a file manager do not hammer your backend. Run a filesystem test suite against it and fix what breaks.",
    difficulty: "ADVANCED",
    estimatedHours: 20,
    popularity: 0.5,
    tags: ["systems", "operating-systems"],
    languages: ["c", "rust", "go", "python"],
    concepts: ["VFS operations and inodes", "FUSE callbacks", "caching and consistency", "permissions", "mapping foreign data to files"],
    sourceUrl: "https://github.com/libfuse/libfuse",
  },
  {
    slug: "boot-a-tiny-os-kernel",
    title: "Boot a tiny OS kernel",
    summary: "Write a kernel that boots on QEMU, prints to the screen, handles interrupts and schedules two tasks.",
    description:
      "Produce a bootable image, get control of the CPU with no operating system underneath you, and print text by writing directly to VGA memory or a serial port. Then set up a GDT and IDT, handle the timer and keyboard interrupts, and add a physical frame allocator and paging so you can map memory. Each milestone is visible in the emulator, which keeps motivation high.\n\nWith memory and interrupts working, write a round-robin scheduler that switches between two kernel tasks, then a simple heap so you can allocate. Stretch goals include user mode with system calls, a ramdisk filesystem and a shell running on top of it. Even the first few steps give you an unusually clear picture of what an operating system is.",
    difficulty: "ADVANCED",
    estimatedHours: 60,
    popularity: 0.6,
    tags: ["operating-systems", "systems", "embedded"],
    languages: ["rust", "c", "zig"],
    concepts: ["boot process and bare metal", "interrupt descriptor tables", "paging and frame allocation", "context switching", "system calls"],
    sourceUrl: "https://os.phil-opp.com/",
  },
  {
    slug: "reimplement-coreutils",
    title: "Reimplement coreutils: ls, cat, wc, grep, head",
    summary: "Rebuild a handful of everyday command-line tools with correct flags, exit codes and streaming input.",
    description:
      "Pick five commands you use daily and rebuild them faithfully. cat and wc teach buffered streaming so a multi-gigabyte file never sits in memory. ls teaches stat, permissions bits, sorting and column layout that adapts to terminal width. grep teaches regular expressions, exit codes that scripts rely on, and reading from stdin when no file is given.\n\nThe discipline of matching the real tools' behaviour — flags, error messages to stderr, handling of missing files, binary data — is the actual lesson. Finish with a small benchmark against the system versions and a test suite that runs both and diffs the output.",
    difficulty: "BEGINNER",
    estimatedHours: 6,
    popularity: 0.7,
    tags: ["cli", "systems"],
    languages: ["rust", "go", "c", "zig"],
    concepts: ["argument parsing", "streaming I/O", "file metadata and permissions", "exit codes and stderr", "regular expressions"],
  },
  {
    slug: "lock-free-queue",
    title: "Implement a lock-free concurrent queue",
    summary: "Build a multi-producer, multi-consumer queue with atomics only, then prove to yourself it is correct.",
    description:
      "Implement the Michael–Scott queue or a bounded ring buffer (as in Dmitry Vyukov's MPMC design) using compare-and-swap and carefully chosen memory orderings. The first version will probably be wrong in a way that only appears under contention, which is precisely the point: you will learn to reason about linearisability, the ABA problem and why acquire/release matter.\n\nWrite a stress test that hammers the queue from many threads and checks that every element is delivered exactly once, run it under a race detector or a model checker such as loom, and benchmark against a mutex-protected queue. Sometimes the mutex wins, and understanding when is as valuable as the data structure itself.",
    difficulty: "ADVANCED",
    estimatedHours: 14,
    popularity: 0.4,
    tags: ["concurrency", "data-structures", "systems"],
    languages: ["cpp", "rust", "c"],
    concepts: ["compare-and-swap", "memory ordering", "the ABA problem", "linearisability", "stress testing concurrent code"],
    sourceUrl: "https://mirrors.edge.kernel.org/pub/linux/kernel/people/paulmck/perfbook/perfbook.html",
  },
  {
    slug: "virtual-memory-simulator",
    title: "Build a virtual memory and page-replacement simulator",
    summary: "Simulate page tables, TLB hits and eviction policies on real memory traces and visualise the results.",
    description:
      "Model a process's address space, a page table, a small TLB and a fixed set of physical frames. Feed it a trace of memory accesses (you can record one from a real program with a tracing tool) and count page faults under FIFO, LRU, Clock and optimal replacement. The differences between policies on real traces are far more instructive than the textbook diagrams.\n\nAdd multi-level page tables to see how much space they save, simulate a TLB with different sizes and associativity, and plot fault rate against frame count to find the knee of the curve. A small interactive visualiser that steps through accesses one at a time turns this into a teaching tool.",
    difficulty: "INTERMEDIATE",
    estimatedHours: 8,
    popularity: 0.35,
    tags: ["operating-systems", "systems", "simulation", "visualization"],
    languages: ["python", "rust", "typescript"],
    concepts: ["page tables and TLBs", "replacement policies", "trace-driven simulation", "locality of reference", "plotting results"],
  },
  {
    slug: "process-supervisor",
    title: "Build a process supervisor",
    summary: "Write a small init-like daemon that starts services, restarts them on failure and exposes their status.",
    description:
      "Read a config file describing services, spawn each one, capture their stdout and stderr into log files, and watch for exit. When a service dies, restart it with exponential backoff; when it flaps too often, mark it failed. Handle SIGTERM by stopping children in dependency order and reaping zombies correctly so nothing is orphaned.\n\nThen add the operational niceties that make tools like systemd, supervisord and s6 pleasant: a control socket and CLI to start, stop and tail logs; health checks that hit an HTTP endpoint; environment and working-directory configuration; and running as PID 1 inside a container, which has its own quirks around signal defaults.",
    difficulty: "INTERMEDIATE",
    estimatedHours: 10,
    popularity: 0.4,
    tags: ["systems", "operating-systems", "cli", "automation"],
    languages: ["go", "rust", "c"],
    concepts: ["process lifecycle and reaping", "signal handling", "exponential backoff", "Unix domain sockets", "PID 1 responsibilities"],
  },
  {
    slug: "strace-clone-with-ptrace",
    title: "Write an strace clone with ptrace",
    summary: "Trace another process's system calls, decode their arguments and print them like the real strace.",
    description:
      "Use ptrace to attach to a child process, stop it at every system-call entry and exit, read the registers to find the syscall number and arguments, and print them. Decoding a few common calls (open, read, write, connect) with their flags and reading strings out of the traced process's memory turns a wall of numbers into something readable.\n\nExtend it to follow forks and threads, filter by syscall, time each call, and produce a summary table like strace -c. You will come away understanding how debuggers stop processes, how syscalls cross the user/kernel boundary and why observing a program changes its timing.",
    difficulty: "ADVANCED",
    estimatedHours: 12,
    popularity: 0.45,
    tags: ["systems", "operating-systems", "devtools"],
    languages: ["c", "rust"],
    concepts: ["ptrace", "system call ABI", "reading remote process memory", "signals and stops", "following forks"],
    sourceUrl: "https://man7.org/linux/man-pages/man2/ptrace.2.html",
  },
  {
    slug: "system-monitor-tui",
    title: "Build a system monitor like htop",
    summary: "Read live CPU, memory and process data from the OS and render it in a responsive terminal UI.",
    description:
      "On Linux almost everything you need is in /proc: per-CPU jiffies in /proc/stat, memory in /proc/meminfo and one directory per process with its command line, state and resource usage. Sample them once a second, compute deltas for CPU percentages, and draw bars, sparklines and a sortable process table in the terminal with a TUI library or raw escape sequences.\n\nMake it feel good to use: keyboard navigation, sorting by column, filtering, killing a process with confirmation, and a layout that reflows when the terminal is resized. Support macOS through sysctl and libproc if you want a portable tool. Measuring your own monitor's CPU usage is a fun exercise in efficiency.",
    difficulty: "INTERMEDIATE",
    estimatedHours: 10,
    popularity: 0.6,
    tags: ["terminal", "systems", "cli", "visualization"],
    languages: ["rust", "go", "c", "python"],
    concepts: ["/proc and sysctl", "terminal rendering", "sampling and deltas", "keyboard-driven UI", "process signals"],
  },
];
