import type { SeedProject } from "../types";

export const WEB_PROJECTS: SeedProject[] = [
  {
    slug: "static-site-generator",
    title: "Create a static-site generator",
    summary: "Turn a folder of Markdown into a fast website with templates, tags, RSS and incremental rebuilds.",
    description:
      "Walk a content directory, parse front matter and Markdown, render each page through a layout template, and write HTML into an output folder. Add index pages, tag archives, an RSS feed and a sitemap and you have the core of Jekyll, Hugo or Eleventy. Because your own blog is the test case, every feature you add is immediately useful.\n\nThe second half is developer experience: a dev server with live reload, incremental builds that only re-render what changed, asset hashing for cache busting, syntax highlighting for code blocks and a plugin hook so others could extend it. Measuring build time on a thousand generated posts will push you toward caching and parallelism.",
    difficulty: "BEGINNER",
    estimatedHours: 6,
    popularity: 0.8,
    tags: ["web", "devtools", "cli"],
    languages: ["typescript", "go", "python", "rust"],
    concepts: ["Markdown and front matter parsing", "templating", "file watching and live reload", "incremental builds", "feeds and sitemaps"],
    sourceUrl: "https://www.11ty.dev/",
  },
  {
    slug: "real-time-collaborative-editor",
    title: "Create a real-time collaborative editor",
    summary: "Let several people edit the same document at once with live cursors and conflict-free merging.",
    description:
      "Multiple clients edit a shared text; every keystroke becomes an operation broadcast to the others; and everyone must converge to the same document even when edits happen concurrently. Choose your weapon: operational transformation with a central server that transforms operations, or a CRDT where each character has a unique identifier and merges commute. Either way you will implement it, test it with randomised concurrent edits, and see it survive.\n\nOn top of the core, build presence (coloured cursors and selections), a WebSocket relay, offline editing that syncs on reconnect, and persistence with document history. Rich text with formatting marks is a worthy stretch goal. This is one of the most satisfying demos you can build, and the underlying theory is used by Google Docs, Figma and Notion.",
    difficulty: "ADVANCED",
    estimatedHours: 30,
    popularity: 0.75,
    tags: ["web", "frontend", "distributed-systems", "backend"],
    languages: ["typescript"],
    concepts: ["operational transformation or CRDTs", "WebSocket broadcast", "presence and cursors", "offline sync", "document persistence and history"],
    sourceUrl: "https://docs.yjs.dev/",
  },
  {
    slug: "build-a-virtual-dom",
    title: "Build a virtual DOM and mini React",
    summary: "Write createElement, a diffing renderer, components with state and hooks — then run a real app on it.",
    description:
      "Represent UI as plain objects (type, props, children), render them to real DOM nodes, and when state changes, diff the new tree against the old one and patch only what changed. That reconciliation loop is the core idea behind React, Preact and their relatives, and it fits in a few hundred lines. Add function components, then useState and useEffect with a hook index per component instance.\n\nThen deal with what makes real frameworks hard: keyed list diffing that moves nodes instead of recreating them, event delegation, batching updates, avoiding re-rendering unchanged subtrees, and refs. Port a to-do app or a small dashboard onto your framework and profile it. Reading Preact's source afterwards feels like reading your own code with better handwriting.",
    difficulty: "INTERMEDIATE",
    estimatedHours: 10,
    popularity: 0.7,
    tags: ["frontend", "web"],
    languages: ["typescript", "javascript"],
    concepts: ["virtual DOM trees", "reconciliation and diffing", "keyed list updates", "hooks and component state", "batched rendering"],
  },
  {
    slug: "url-shortener-with-analytics",
    title: "Build a URL shortener with click analytics",
    summary: "Create short links, redirect fast, and record clicks with a small dashboard of referrers and geography.",
    description:
      "The core is a table mapping a short code to a URL, a POST endpoint that generates codes (base62 of an id, or random with collision checks), and a redirect endpoint that must be fast because it is on the critical path of every click. Add link expiry, custom aliases and QR codes for good measure.\n\nAnalytics is where it becomes interesting: record each click asynchronously so redirects stay quick, aggregate by day, referrer, country and device, and show it on a small dashboard. Consider what happens at scale — caching hot links, rate limiting creation, and abuse controls such as blocklists and malware checks. It is a compact project that touches almost every part of a web backend.",
    difficulty: "BEGINNER",
    estimatedHours: 3,
    popularity: 0.7,
    tags: ["backend", "web"],
    languages: ["typescript", "go", "python"],
    concepts: ["short code generation", "HTTP redirects", "asynchronous event recording", "aggregation queries", "caching hot paths"],
  },
  {
    slug: "markdown-editor-with-live-preview",
    title: "Build a Markdown editor with live preview",
    summary: "Write your own Markdown parser and render a split-pane editor with synchronized scrolling.",
    description:
      "Rather than importing a Markdown library, write the parser: a block pass that recognises headings, paragraphs, lists, code fences and blockquotes, and an inline pass for emphasis, links, images and inline code. Render to an HTML tree and update the preview on every keystroke. The CommonMark spec is your test suite — pick a subset and pass its examples.\n\nOn the editor side, add synchronized scrolling between the source and the preview, keyboard shortcuts for bold and links, a toolbar, local persistence, and export to HTML or PDF. Handling edge cases like nested lists and lazy continuation lines is a satisfying puzzle, and the result is a tool you will actually use.",
    difficulty: "BEGINNER",
    estimatedHours: 5,
    popularity: 0.6,
    tags: ["frontend", "web"],
    languages: ["typescript", "javascript"],
    concepts: ["block and inline parsing", "AST to HTML rendering", "editor state handling", "synchronized scrolling", "spec-driven testing"],
    sourceUrl: "https://spec.commonmark.org/",
  },
  {
    slug: "kanban-board-with-drag-and-drop",
    title: "Build a Kanban board with drag and drop",
    summary: "Create a Trello-style board with smooth drag and drop, keyboard reordering and local persistence.",
    description:
      "Columns of cards, cards that move between columns, and an interaction that has to feel right: pointer-based dragging with a ghost element, drop indicators, auto-scrolling near the edges and animations that keep the layout stable. Implement it with pointer events yourself before reaching for a library so you understand hit-testing and reordering logic.\n\nMake it accessible: cards must be movable with the keyboard and announced to screen readers. Persist the board locally, add filtering, labels and due dates, and then sync to a small backend so it works across devices. It is a beginner-friendly project with an unusually high ceiling for polish.",
    difficulty: "BEGINNER",
    estimatedHours: 6,
    popularity: 0.6,
    tags: ["frontend", "web"],
    languages: ["typescript"],
    concepts: ["pointer events and drag state", "list reordering", "accessible drag and drop", "optimistic UI", "local persistence"],
  },
  {
    slug: "spaced-repetition-flashcards",
    title: "Build a spaced-repetition flashcards app",
    summary: "Implement the SM-2 scheduling algorithm and a review interface that keeps you coming back.",
    description:
      "Spaced repetition works because it schedules each card just before you would forget it. Implement the SM-2 algorithm used by early Anki: each review gets a grade, which updates an ease factor and the next interval. Build the deck and card models, a review session that shows due cards, and statistics that show retention and upcoming workload.\n\nThen make it yours: cloze deletions, images and audio on cards, import from CSV, and a heat-map of daily reviews. If you build it as a mobile app, add notifications for due reviews. Comparing SM-2 with newer algorithms such as FSRS is a good excuse to read some memory research.",
    difficulty: "BEGINNER",
    estimatedHours: 6,
    popularity: 0.55,
    tags: ["web", "frontend", "backend", "algorithms"],
    languages: ["typescript", "kotlin", "swift"],
    concepts: ["SM-2 scheduling", "review session state", "data modelling", "statistics and charts", "import/export"],
  },
  {
    slug: "http-framework-from-scratch",
    title: "Build an Express-style HTTP framework",
    summary: "Write routing, middleware, body parsing and error handling on top of your language's raw HTTP server.",
    description:
      "Every web framework is a small set of ideas: match a method and path (with parameters and wildcards) to a handler, run a chain of middleware functions that can short-circuit or pass control on, parse bodies, and turn thrown errors into responses. Implement those on top of the raw HTTP server in your language and you will understand what Express, Flask, Gin and Axum do for you.\n\nDesign the router as a radix tree for speed, support route groups and per-group middleware, add typed request validation, static file serving and cookie handling, and write a test helper that exercises handlers without opening a socket. Benchmark it against the framework you normally use; the results are often surprising.",
    difficulty: "INTERMEDIATE",
    estimatedHours: 8,
    popularity: 0.6,
    tags: ["backend", "web"],
    languages: ["typescript", "python", "go", "rust"],
    concepts: ["radix tree routing", "middleware chains", "request body parsing", "error handling design", "testing HTTP handlers"],
  },
  {
    slug: "web-scraper-with-change-alerts",
    title: "Build a web scraper that alerts you when pages change",
    summary: "Fetch pages on a schedule, extract what matters, diff against the last version and notify you.",
    description:
      "Fetch a page, pull out the interesting part with CSS selectors, normalise it and store a snapshot; on the next run, diff the new snapshot against the old one and, if it changed, send yourself a notification. Track a product price, a job board, a changelog or a concert listing — the utility is immediate.\n\nDo it responsibly and robustly: respect robots.txt and rate limits, set a real user agent, retry with backoff, handle pages that render with JavaScript by driving a headless browser, and store history so you can see how a value changed over time. A small web UI to add watches and view diffs turns the script into a product.",
    difficulty: "BEGINNER",
    estimatedHours: 4,
    popularity: 0.55,
    tags: ["automation", "web", "backend"],
    languages: ["python", "typescript", "go"],
    concepts: ["HTML parsing and selectors", "scheduling", "diffing snapshots", "polite crawling", "headless browsers"],
    sourceUrl: "https://www.rfc-editor.org/rfc/rfc9309",
  },
  {
    slug: "self-hosted-rss-reader",
    title: "Build a self-hosted RSS reader with search",
    summary: "Fetch and parse feeds, deduplicate entries, and add full-text search and a keyboard-driven reading UI.",
    description:
      "Parse RSS and Atom (they differ in annoying ways), fetch feeds on a schedule with conditional requests (ETag, Last-Modified) so you are a polite client, and store entries deduplicated by GUID. Build a reading interface with unread counts, keyboard navigation (j/k to move, o to open) and a reader mode that extracts article content.\n\nThen add search over everything you have ever fetched: an inverted index or your database's full-text features, with ranking. Feed discovery from a site URL, OPML import/export, rules that auto-tag or hide entries, and a mobile-friendly layout round it out. It is a project you can genuinely live in every day.",
    difficulty: "INTERMEDIATE",
    estimatedHours: 10,
    popularity: 0.5,
    tags: ["web", "backend", "information-retrieval"],
    languages: ["typescript", "go", "python"],
    concepts: ["feed parsing (RSS/Atom)", "conditional HTTP requests", "deduplication", "full-text search", "keyboard-first UI"],
  },
  {
    slug: "client-side-router-library",
    title: "Build a client-side router library",
    summary: "Implement history-based routing with nested routes, params, guards and lazy loading.",
    description:
      "A single-page app needs to map URLs to views without reloading. Implement path matching with parameters and wildcards, integrate with the History API (pushState, popstate) so back and forward work, and render the matched component. Then support nested routes with outlets, route guards for redirects, query-string parsing and scroll restoration.\n\nAdd code-splitting so route components load lazily, link components that prefetch on hover, and a declarative route table with type-safe params. Testing it means simulating navigation in a fake history. By the end you will understand every option in your favourite router's documentation.",
    difficulty: "BEGINNER",
    estimatedHours: 4,
    popularity: 0.45,
    tags: ["frontend", "web"],
    languages: ["typescript", "javascript"],
    concepts: ["History API", "path pattern matching", "nested routes", "navigation guards", "lazy loading"],
  },
  {
    slug: "reactive-state-management-library",
    title: "Write a reactive state-management library",
    summary: "Build signals or a store with fine-grained subscriptions, derived values and devtools time travel.",
    description:
      "Implement reactive primitives: a signal holds a value and tracks who read it, a computed value re-derives lazily when its dependencies change, and an effect re-runs when anything it read changes. Automatic dependency tracking is the trick — record reads during execution — and getting it right without leaks or glitches (diamond dependencies, stale reads) is the real work.\n\nAlternatively, or additionally, build a store with actions and reducers, middleware, selectors with memoisation and a devtools panel that records every action so you can time-travel. Bind either to a UI framework and compare render counts against a naive approach. Studying Solid, Preact Signals, Zustand and Redux side by side afterwards is illuminating.",
    difficulty: "INTERMEDIATE",
    estimatedHours: 8,
    popularity: 0.5,
    tags: ["frontend", "web"],
    languages: ["typescript", "javascript"],
    concepts: ["automatic dependency tracking", "derived and memoised values", "glitch-free updates", "subscriptions and batching", "devtools and time travel"],
  },
  {
    slug: "feature-flag-service",
    title: "Build a feature-flag service",
    summary: "Serve flags with percentage rollouts, targeting rules and a client SDK that updates in real time.",
    description:
      "Define flags with variants, targeting rules (user attributes, segments) and percentage rollouts that hash the user id so a person sees the same variant every time. Build an API to evaluate flags for a context, an admin UI to edit them with an audit log, and a client SDK that caches flags locally and receives updates over server-sent events.\n\nGet the operational details right: safe defaults when the service is unreachable, evaluation that is fast enough for the request path, kill switches, scheduled changes and environment separation. Then add experiment assignment and basic exposure logging so the same system can run A/B tests. It is a small product with big leverage.",
    difficulty: "INTERMEDIATE",
    estimatedHours: 10,
    popularity: 0.45,
    tags: ["backend", "web", "devtools"],
    languages: ["typescript", "go", "java", "csharp"],
    concepts: ["consistent hashing for rollouts", "rule evaluation engines", "server-sent events", "SDK design and caching", "audit logs"],
  },
  {
    slug: "offline-first-notes-pwa",
    title: "Build an offline-first notes PWA with sync",
    summary: "Make a notes app that works with no network, installs like a native app and syncs when back online.",
    description:
      "Store notes in IndexedDB, register a service worker that caches the app shell so it loads offline, and add a manifest so it installs on phones and desktops. Then build sync: queue local changes, push them when connectivity returns, pull remote changes and merge — last-writer-wins per field to start, a CRDT if you want conflict-free merging.\n\nThe interesting problems are the ones native apps face: background sync, handling the same note edited on two devices, showing sync status honestly, and migrating local data when your schema changes. Add full-text search over local notes and Markdown rendering, and you have a genuinely useful app that runs anywhere a browser does.",
    difficulty: "INTERMEDIATE",
    estimatedHours: 12,
    popularity: 0.55,
    tags: ["web", "frontend", "mobile"],
    languages: ["typescript"],
    concepts: ["service workers and caching", "IndexedDB", "sync queues and conflict handling", "web app manifests", "schema migrations on the client"],
    sourceUrl: "https://developer.mozilla.org/en-US/docs/Web/API/Service_Worker_API",
  },
  {
    slug: "webhook-delivery-service",
    title: "Build a webhook delivery service",
    summary: "Deliver signed events to customer URLs reliably with retries, ordering guarantees and a delivery log.",
    description:
      "Producers emit events; subscribers register URLs; your service delivers each event as an HTTP POST with an HMAC signature header, and keeps trying — with exponential backoff and jitter — until it gets a 2xx or gives up. Store every attempt so users can see exactly what happened and replay failed deliveries from a dashboard.\n\nDetails separate toy from tool: signing with rotating secrets, timestamp headers to prevent replay, per-endpoint concurrency and ordering, circuit breaking for endpoints that are down, and protecting yourself from slow or malicious endpoints (timeouts, redirect limits, blocking private IP ranges). Build a receiver library too, so verifying signatures is easy for your users.",
    difficulty: "INTERMEDIATE",
    estimatedHours: 8,
    popularity: 0.4,
    tags: ["backend", "web", "distributed-systems"],
    languages: ["typescript", "go", "python"],
    concepts: ["HMAC request signing", "retry with backoff and jitter", "delivery logs and replay", "circuit breakers", "SSRF protections"],
  },
  {
    slug: "toy-browser-layout-engine",
    title: "Build a toy browser layout engine",
    summary: "Parse HTML and CSS, build a style tree, compute a box layout and paint rectangles — a browser in miniature.",
    description:
      "Write a small HTML parser producing a DOM tree and a CSS parser producing rules, then match selectors to nodes to build a styled tree. Implement the CSS box model for block layout — margins, padding, borders, widths that fill the container, heights from content — and produce a layout tree of positioned boxes. Paint it to an image and you will see your own page rendered by your own engine.\n\nThen add inline layout and text with a real font rasteriser, floats or flexbox, and hit testing for clicks. Every feature reveals why browsers are so complicated and why the CSS spec reads the way it does. Matt Brubeck's series is a proven path through it.",
    difficulty: "ADVANCED",
    estimatedHours: 30,
    popularity: 0.5,
    tags: ["frontend", "graphics", "web"],
    languages: ["rust", "typescript"],
    concepts: ["HTML/CSS parsing", "selector matching", "the box model", "block and inline layout", "painting to a canvas"],
    sourceUrl: "https://limpet.net/mbrubeck/2014/08/08/toy-layout-engine-1.html",
  },
  {
    slug: "accessible-component-library",
    title: "Build an accessible UI component library",
    summary: "Implement dialog, menu, combobox and tabs that pass the ARIA Authoring Practices and real screen-reader tests.",
    description:
      "Most component libraries look accessible and are not. Build the hard ones properly: a modal dialog with focus trapping and restoration, a menu with roving tabindex and typeahead, a combobox with listbox popup and live announcements, and tabs with automatic and manual activation. Follow the ARIA Authoring Practices patterns for roles, states and keyboard interaction.\n\nTest with a real screen reader (VoiceOver, NVDA) and with automated tooling, respect reduced-motion preferences, and make styling themeable without breaking semantics. Publish it with documentation that shows keyboard shortcuts for every component. You will come out understanding the accessibility tree and focus management better than most frontend engineers.",
    difficulty: "INTERMEDIATE",
    estimatedHours: 12,
    popularity: 0.5,
    tags: ["frontend", "web"],
    languages: ["typescript"],
    concepts: ["ARIA roles and states", "focus management", "keyboard interaction patterns", "screen-reader testing", "headless component design"],
    sourceUrl: "https://www.w3.org/WAI/ARIA/apg/",
  },
];
