import type { SeedDifficulty } from "./types";

/**
 * Latent interest archetypes for synthetic users.
 *
 * Each archetype describes *why* a synthetic user behaves the way they do:
 * tag affinities in [-1, 1] (negative values are genuine dislikes), language
 * affinities, a difficulty preference and a typical exploration preference.
 * Synthetic users are blends of a primary and a secondary archetype plus noise,
 * so collaborative filtering has real structure to discover while no two users
 * are identical.
 */
export interface Archetype {
  key: string;
  label: string;
  /** Tag slug → affinity in [-1, 1]. Unlisted tags are neutral (0). */
  tags: Record<string, number>;
  /** Language slug → affinity in [-1, 1]. Unlisted languages are neutral (0). */
  languages: Record<string, number>;
  /** Difficulty → affinity in [-1, 1]. */
  difficulty: Record<SeedDifficulty, number>;
  /** Typical exploration preference (0 = familiar, 1 = adventurous). */
  exploration: number;
}

export const ARCHETYPES: Archetype[] = [
  {
    key: "systems-hacker",
    label: "Systems hacker",
    tags: {
      systems: 1.0,
      "operating-systems": 0.9,
      concurrency: 0.7,
      databases: 0.6,
      networking: 0.6,
      compilers: 0.4,
      cli: 0.5,
      emulation: 0.3,
      frontend: -0.7,
      mobile: -0.8,
      "creative-coding": -0.4,
      web: -0.3,
    },
    languages: { rust: 0.9, c: 0.8, zig: 0.6, go: 0.4, typescript: -0.3, javascript: -0.5 },
    difficulty: { BEGINNER: -0.3, INTERMEDIATE: 0.4, ADVANCED: 0.7 },
    exploration: 0.3,
  },
  {
    key: "database-builder",
    label: "Database builder",
    tags: {
      databases: 1.0,
      "data-structures": 0.7,
      systems: 0.7,
      "distributed-systems": 0.6,
      "data-engineering": 0.5,
      backend: 0.4,
      concurrency: 0.3,
      graphics: -0.5,
      "game-development": -0.5,
      mobile: -0.6,
      "creative-coding": -0.4,
    },
    languages: { rust: 0.7, go: 0.7, java: 0.4, cpp: 0.4, c: 0.3 },
    difficulty: { BEGINNER: -0.2, INTERMEDIATE: 0.5, ADVANCED: 0.6 },
    exploration: 0.3,
  },
  {
    key: "graphics-artist",
    label: "Graphics artist",
    tags: {
      graphics: 1.0,
      webgl: 0.9,
      "creative-coding": 0.9,
      "procedural-generation": 0.8,
      simulation: 0.6,
      visualization: 0.5,
      "game-development": 0.4,
      databases: -0.7,
      backend: -0.5,
      security: -0.5,
      "distributed-systems": -0.6,
      "data-engineering": -0.6,
    },
    languages: { typescript: 0.8, glsl: 0.9, cpp: 0.4, rust: 0.3, java: -0.4 },
    difficulty: { BEGINNER: 0.2, INTERMEDIATE: 0.5, ADVANCED: 0.2 },
    exploration: 0.5,
  },
  {
    key: "web-builder",
    label: "Web builder",
    tags: {
      web: 1.0,
      frontend: 0.9,
      backend: 0.7,
      devtools: 0.4,
      cli: 0.2,
      automation: 0.3,
      embedded: -0.8,
      "operating-systems": -0.6,
      emulation: -0.5,
      cryptography: -0.3,
      iot: -0.5,
    },
    languages: { typescript: 1.0, javascript: 0.7, go: 0.3, python: 0.3, c: -0.6, cpp: -0.5 },
    difficulty: { BEGINNER: 0.4, INTERMEDIATE: 0.5, ADVANCED: -0.2 },
    exploration: 0.4,
  },
  {
    key: "ml-explorer",
    label: "ML explorer",
    tags: {
      "machine-learning": 1.0,
      nlp: 0.8,
      "recommendation-systems": 0.7,
      "computer-vision": 0.6,
      "information-retrieval": 0.6,
      "data-engineering": 0.4,
      algorithms: 0.4,
      embedded: -0.6,
      "operating-systems": -0.5,
      graphics: -0.2,
      terminal: -0.3,
    },
    languages: { python: 1.0, typescript: 0.3, rust: 0.2, c: -0.4 },
    difficulty: { BEGINNER: 0.2, INTERMEDIATE: 0.6, ADVANCED: 0.2 },
    exploration: 0.45,
  },
  {
    key: "game-developer",
    label: "Game developer",
    tags: {
      "game-development": 1.0,
      multiplayer: 0.8,
      "procedural-generation": 0.7,
      graphics: 0.6,
      simulation: 0.6,
      emulation: 0.5,
      audio: 0.4,
      networking: 0.3,
      databases: -0.5,
      "data-engineering": -0.7,
      security: -0.4,
      automation: -0.3,
    },
    languages: { csharp: 0.7, cpp: 0.6, rust: 0.5, typescript: 0.5, java: -0.2 },
    difficulty: { BEGINNER: 0.3, INTERMEDIATE: 0.6, ADVANCED: 0.1 },
    exploration: 0.4,
  },
  {
    key: "security-researcher",
    label: "Security researcher",
    tags: {
      security: 1.0,
      cryptography: 0.9,
      networking: 0.7,
      systems: 0.5,
      "operating-systems": 0.4,
      cli: 0.3,
      "creative-coding": -0.6,
      "game-development": -0.4,
      frontend: -0.4,
      audio: -0.5,
    },
    languages: { rust: 0.7, go: 0.7, python: 0.5, c: 0.5, javascript: -0.3 },
    difficulty: { BEGINNER: -0.2, INTERMEDIATE: 0.5, ADVANCED: 0.6 },
    exploration: 0.3,
  },
  {
    key: "distributed-backend",
    label: "Distributed backend engineer",
    tags: {
      "distributed-systems": 1.0,
      backend: 0.8,
      networking: 0.6,
      databases: 0.6,
      "data-engineering": 0.5,
      concurrency: 0.5,
      systems: 0.4,
      graphics: -0.6,
      "creative-coding": -0.6,
      mobile: -0.5,
      audio: -0.5,
    },
    languages: { go: 1.0, java: 0.5, rust: 0.5, kotlin: 0.3, glsl: -0.5 },
    difficulty: { BEGINNER: -0.1, INTERMEDIATE: 0.6, ADVANCED: 0.5 },
    exploration: 0.3,
  },
  {
    key: "hardware-tinkerer",
    label: "Hardware tinkerer",
    tags: {
      embedded: 1.0,
      iot: 1.0,
      automation: 0.5,
      systems: 0.4,
      emulation: 0.4,
      audio: 0.3,
      web: -0.5,
      frontend: -0.6,
      "machine-learning": -0.3,
      "distributed-systems": -0.4,
    },
    languages: { c: 0.9, cpp: 0.7, rust: 0.5, python: 0.4, typescript: -0.4 },
    difficulty: { BEGINNER: 0.3, INTERMEDIATE: 0.5, ADVANCED: 0.1 },
    exploration: 0.4,
  },
  {
    key: "language-designer",
    label: "Language designer",
    tags: {
      "programming-languages": 1.0,
      compilers: 1.0,
      algorithms: 0.6,
      devtools: 0.6,
      systems: 0.4,
      terminal: 0.3,
      mobile: -0.7,
      iot: -0.6,
      frontend: -0.3,
      "game-development": -0.2,
    },
    languages: { rust: 0.8, c: 0.5, typescript: 0.4, zig: 0.4, go: 0.3, kotlin: -0.2 },
    difficulty: { BEGINNER: -0.2, INTERMEDIATE: 0.5, ADVANCED: 0.7 },
    exploration: 0.35,
  },
  {
    key: "mobile-maker",
    label: "Mobile maker",
    tags: {
      mobile: 1.0,
      frontend: 0.5,
      web: 0.4,
      "computer-vision": 0.3,
      audio: 0.2,
      "operating-systems": -0.7,
      compilers: -0.6,
      "distributed-systems": -0.5,
      databases: -0.2,
      emulation: -0.4,
    },
    languages: { kotlin: 0.9, swift: 0.9, typescript: 0.4, c: -0.5, rust: -0.3 },
    difficulty: { BEGINNER: 0.5, INTERMEDIATE: 0.4, ADVANCED: -0.3 },
    exploration: 0.45,
  },
  {
    key: "data-engineer",
    label: "Data engineer",
    tags: {
      "data-engineering": 1.0,
      databases: 0.7,
      "information-retrieval": 0.6,
      "distributed-systems": 0.5,
      backend: 0.4,
      automation: 0.4,
      algorithms: 0.3,
      graphics: -0.5,
      "game-development": -0.6,
      "creative-coding": -0.5,
      emulation: -0.4,
    },
    languages: { python: 0.8, go: 0.5, java: 0.5, rust: 0.4, kotlin: 0.3, glsl: -0.6 },
    difficulty: { BEGINNER: 0.0, INTERMEDIATE: 0.6, ADVANCED: 0.3 },
    exploration: 0.35,
  },
  {
    key: "creative-coder",
    label: "Creative coder",
    tags: {
      "creative-coding": 1.0,
      audio: 0.8,
      "procedural-generation": 0.7,
      graphics: 0.6,
      web: 0.4,
      simulation: 0.4,
      webgl: 0.5,
      security: -0.5,
      databases: -0.5,
      "distributed-systems": -0.4,
      "data-engineering": -0.5,
    },
    languages: { typescript: 0.9, javascript: 0.6, python: 0.5, glsl: 0.5, java: -0.4, go: -0.3 },
    difficulty: { BEGINNER: 0.5, INTERMEDIATE: 0.4, ADVANCED: -0.2 },
    exploration: 0.6,
  },
  {
    key: "algorithms-tinkerer",
    label: "Algorithms tinkerer",
    tags: {
      algorithms: 1.0,
      "data-structures": 0.9,
      visualization: 0.4,
      cli: 0.4,
      compilers: 0.3,
      "game-development": 0.3,
      "information-retrieval": 0.3,
      iot: -0.5,
      mobile: -0.4,
      embedded: -0.4,
    },
    languages: { python: 0.7, rust: 0.5, cpp: 0.5, typescript: 0.4, swift: -0.3 },
    difficulty: { BEGINNER: 0.3, INTERMEDIATE: 0.5, ADVANCED: 0.2 },
    exploration: 0.5,
  },
  {
    key: "cli-toolsmith",
    label: "CLI toolsmith",
    tags: {
      devtools: 1.0,
      cli: 0.9,
      terminal: 0.9,
      automation: 0.6,
      systems: 0.4,
      "programming-languages": 0.3,
      graphics: -0.4,
      mobile: -0.5,
      "machine-learning": -0.3,
      webgl: -0.5,
    },
    languages: { rust: 0.9, go: 0.8, typescript: 0.4, python: 0.3, swift: -0.4 },
    difficulty: { BEGINNER: 0.2, INTERMEDIATE: 0.6, ADVANCED: 0.2 },
    exploration: 0.35,
  },
];

/** Deterministic pool of display names for synthetic users. */
export const SYNTHETIC_USER_NAMES = [
  "Ada",
  "Bram",
  "Chidi",
  "Dana",
  "Elin",
  "Farid",
  "Greta",
  "Hiro",
  "Ines",
  "Jonas",
  "Kai",
  "Lena",
  "Mateo",
  "Noor",
  "Otis",
  "Priya",
  "Quinn",
  "Rafael",
  "Sasha",
  "Tomas",
  "Uma",
  "Viktor",
  "Wren",
  "Ximena",
  "Yusuf",
  "Zara",
  "Arlo",
  "Bea",
  "Caspian",
  "Delphine",
] as const;
